import type { PageText } from "@/lib/i18n/text";

const en = {
  registryFailed: "Patient registry could not be loaded. Check the connection and your clinic access, then retry.",
  selectFromClinic: "Select a patient from the active clinic.",
  noActiveEpisode:
    "This patient has no active care episode. Open the registry and create or reactivate an episode first.",
  nameRequired: "Patient name is required.",
  ageInvalid: "Enter a valid age (0–120).",
  complaintRequired: "Main complaint is required.",
  regionRequired: "Select a body region.",
  screenRequired: "Complete the structured red-flag screen before creating the case.",
  patientRequired: "Select a registry patient with an active care episode before creating the case.",
  saveFailed:
    "Save failed — your input has been kept. Check the connection (or that your account belongs to a clinic) and try again.",
  loadingRegistry: "Loading patient registry…",
  roleRequired: "Only a clinic owner or therapist may create a clinical case.",
  title: "New Patient Case",
  intro:
    "Capture the subjective interview in a structured format. Required fields are marked; everything else can be completed later.",
  linkTitle: "Link registry patient",
  linkSubtitle: "Real clinical cases must belong to one patient and that patient’s active care episode.",
  searchName: "Search patient name",
  searchHint: (n: number) => `Showing at most ${n} matches from the active clinic.`,
  searchPlaceholder: "Type a patient name",
  search: "Search",
  loadingPatients: "Loading patients…",
  retry: "Retry",
  noMatch:
    "No matching patient was found. Create the patient and first care episode in Patient Registry, then return here.",
  patientEpisode: "Patient and active episode",
  selectPatient: "Select a patient…",
  noActiveEpisodeShort: "no active episode",
  linkedTo: (name: string, episode: string) => `Linked to ${name} · episode: ${episode}`,
  details: "Patient Details",
  patientName: "Patient name",
  namePlaceholder: "e.g. Sara Ahmadi",
  age: "Age",
  agePlaceholder: "e.g. 42",
  gender: "Gender",
  select: "Select…",
  female: "Female",
  male: "Male",
  other: "Other",
  region: "Body region",
  presenting: "Presenting Problem",
  mainComplaint: "Main complaint",
  complaintPlaceholder: "In the patient's words — e.g. low back pain radiating to the right buttock",
  painLocation: "Pain location",
  painLocationPlaceholder: "e.g. Lower back, right side",
  duration: "Duration of symptoms",
  durationPlaceholder: "e.g. 8 weeks",
  painIntensity: (value: number) => `Pain intensity — ${value}/10`,
  mechanism: "Mechanism of injury / onset",
  mechanismPlaceholder: "e.g. Gradual onset after desk work",
  aggravating: "Aggravating factors",
  aggravatingPlaceholder: "e.g. Sitting > 30 min, bending",
  easing: "Easing factors",
  easingPlaceholder: "e.g. Walking, lying down",
  functional: "Functional limitations",
  functionalPlaceholder: "e.g. Cannot sit through a work day",
  history: "History & Context",
  medicalHistory: "Medical history",
  medicalPlaceholder: "e.g. Hypertension, diabetes…",
  surgicalHistory: "Surgical history",
  surgicalPlaceholder: "e.g. Left TKA 3 weeks ago",
  imaging: "Imaging findings",
  imagingPlaceholder: "e.g. MRI: L4-L5 disc bulge / Not performed",
  medications: "Current medications",
  medicationsPlaceholder: "e.g. Ibuprofen as needed",
  goal: "Patient goal",
  goalHint: "What does the patient want to get back to?",
  goalPlaceholder: "e.g. Return to pain-free desk work and gym",
  safetyTitle: "Clinical Safety Screen",
  safetySubtitle:
    "Record every item that is present. Unchecked is not considered a negative screen until you explicitly complete it.",
  concernsPresent:
    "One or more safety concerns are present. Document and complete the appropriate medical referral before treatment advice is generated.",
  screenAttest:
    "I completed this structured screen and understand that selected concerns require medical escalation; an empty screen does not replace clinical judgement.",
  clear: "Clear form",
  creating: "Creating…",
  create: "Create case & analyse",
};

export type NewCaseText = typeof en;

export const newCaseText: PageText<NewCaseText> = {
  en,
  fa: {
    registryFailed: "فهرست بیماران بارگذاری نشد. اتصال و دسترسی کلینیک را بررسی و دوباره تلاش کنید.",
    selectFromClinic: "یک بیمار از کلینیک فعال انتخاب کنید.",
    noActiveEpisode:
      "این بیمار دوره درمان فعال ندارد. ابتدا در فهرست بیماران یک دوره درمان ایجاد یا فعال کنید.",
    nameRequired: "نام بیمار الزامی است.",
    ageInvalid: "سن معتبر وارد کنید (۰ تا ۱۲۰).",
    complaintRequired: "شکایت اصلی الزامی است.",
    regionRequired: "ناحیه بدن را انتخاب کنید.",
    screenRequired: "پیش از ثبت پرونده، غربالگری ساختاریافته پرچم قرمز را کامل کنید.",
    patientRequired: "پیش از ثبت پرونده، بیماری با دوره درمان فعال را از فهرست انتخاب کنید.",
    saveFailed:
      "ذخیره انجام نشد — اطلاعات واردشده حفظ شده است. اتصال (یا عضویت حساب در کلینیک) را بررسی و دوباره تلاش کنید.",
    loadingRegistry: "در حال بارگذاری فهرست بیماران…",
    roleRequired: "فقط صاحب کلینیک یا فیزیوتراپیست می‌تواند پرونده بالینی ثبت کند.",
    title: "پرونده جدید بیمار",
    intro: "شرح حال را به‌صورت ساختاریافته ثبت کنید. موارد الزامی مشخص شده‌اند؛ بقیه را بعداً هم می‌توانید کامل کنید.",
    linkTitle: "انتخاب بیمار از فهرست",
    linkSubtitle: "هر پرونده بالینی واقعی باید به یک بیمار و دوره درمان فعال او وصل باشد.",
    searchName: "جستجوی نام بیمار",
    searchHint: (n) => `حداکثر ${n} نتیجه از کلینیک فعال نمایش داده می‌شود.`,
    searchPlaceholder: "نام بیمار را بنویسید",
    search: "جستجو",
    loadingPatients: "در حال بارگذاری بیماران…",
    retry: "تلاش دوباره",
    noMatch: "بیماری پیدا نشد. ابتدا بیمار و اولین دوره درمان را در فهرست بیماران ثبت کنید و به اینجا برگردید.",
    patientEpisode: "بیمار و دوره درمان فعال",
    selectPatient: "انتخاب بیمار…",
    noActiveEpisodeShort: "بدون دوره فعال",
    linkedTo: (name, episode) => `متصل به ${name} · دوره: ${episode}`,
    details: "مشخصات بیمار",
    patientName: "نام بیمار",
    namePlaceholder: "مثلاً سارا احمدی",
    age: "سن",
    agePlaceholder: "مثلاً ۴۲",
    gender: "جنسیت",
    select: "انتخاب…",
    female: "زن",
    male: "مرد",
    other: "سایر",
    region: "ناحیه بدن",
    presenting: "مشکل فعلی",
    mainComplaint: "شکایت اصلی",
    complaintPlaceholder: "به زبان بیمار — مثلاً کمردرد که به باسن راست می‌زند",
    painLocation: "محل درد",
    painLocationPlaceholder: "مثلاً پایین کمر، سمت راست",
    duration: "مدت علائم",
    durationPlaceholder: "مثلاً ۸ هفته",
    painIntensity: (value) => `شدت درد — ${value} از ۱۰`,
    mechanism: "مکانیسم آسیب / نحوه شروع",
    mechanismPlaceholder: "مثلاً شروع تدریجی پس از کار پشت میز",
    aggravating: "عوامل تشدیدکننده",
    aggravatingPlaceholder: "مثلاً نشستن بیش از ۳۰ دقیقه، خم شدن",
    easing: "عوامل تسکین‌دهنده",
    easingPlaceholder: "مثلاً راه رفتن، دراز کشیدن",
    functional: "محدودیت‌های عملکردی",
    functionalPlaceholder: "مثلاً نمی‌تواند یک روز کاری را بنشیند",
    history: "سوابق و زمینه",
    medicalHistory: "سابقه پزشکی",
    medicalPlaceholder: "مثلاً فشار خون، دیابت…",
    surgicalHistory: "سابقه جراحی",
    surgicalPlaceholder: "مثلاً تعویض کامل زانوی چپ ۳ هفته پیش",
    imaging: "یافته‌های تصویربرداری",
    imagingPlaceholder: "مثلاً MRI: برآمدگی دیسک L4-L5 / انجام نشده",
    medications: "داروهای فعلی",
    medicationsPlaceholder: "مثلاً ایبوپروفن در صورت نیاز",
    goal: "هدف بیمار",
    goalHint: "بیمار می‌خواهد به چه فعالیتی برگردد؟",
    goalPlaceholder: "مثلاً بازگشت به کار پشت میز و باشگاه بدون درد",
    safetyTitle: "غربالگری ایمنی بالینی",
    safetySubtitle:
      "هر موردی را که وجود دارد علامت بزنید. تا وقتی غربالگری را صریحاً تکمیل نکنید، علامت نزدن به معنای منفی بودن نیست.",
    concernsPresent:
      "یک یا چند نگرانی ایمنی وجود دارد. پیش از ارائه هر توصیه درمانی، ارجاع پزشکی مناسب را ثبت و انجام دهید.",
    screenAttest:
      "این غربالگری ساختاریافته را کامل کردم و می‌دانم موارد انتخاب‌شده نیازمند ارجاع پزشکی است؛ غربالگری خالی جایگزین قضاوت بالینی نیست.",
    clear: "پاک کردن فرم",
    creating: "در حال ثبت…",
    create: "ثبت پرونده و تحلیل",
  },
};
