import type { PageText } from "@/lib/i18n/text";

const en = {
  minutes: (n: number) => `${n} min`,
  hoursMinutes: (h: number, m: number) => `${h}h ${m}m`,
  daysHours: (d: number, h: number) => `${d}d ${h}h`,
  unknownTime: "Unknown time",
  slaEscalate: "Escalate now",
  slaAnswered: "Answered",
  slaWithin: "Within 4h target",
  slaDue: "Review due",
  slaOverdue: "Overdue >24h",
  senderClinician: "Clinician",
  senderPatient: "Patient",
  senderAi: "AI acknowledgement",
  status: {
    open: "open",
    acknowledged: "acknowledged",
    answered: "answered",
    closed: "closed",
  } as Record<string, string>,
  refreshFailed:
    "Ticket refresh failed. Check the connection and try again; any visible rows may be stale.",
  replyFailed:
    "Reply was not saved. Your text is still here; check assignment and connection, then retry.",
  replySaved: "Reply saved and ticket marked answered.",
  ackFailed: "Acknowledgement was not saved. Check access and retry.",
  ackSaved: "Ticket acknowledged with your authenticated identity.",
  closeFailed:
    "Ticket was not closed. Resolve any linked clinical alert first, then retry; your note is still here.",
  closeSaved: "Ticket closed with an attributed closure note.",
  title: "Patient Messages",
  shortIntro: "Patient messages that need clinician review and a documented response.",
  intro:
    "Review patient messages, triage time-sensitive language and keep replies in the clinical thread.",
  demoTitle: "Demo inbox is empty",
  demoBody:
    "Mock mode does not load or fabricate patient messages. Connect an authenticated clinic database to use the inbox.",
  accessTitle: "Clinical access required",
  accessBody:
    "Ticket PHI is available only to clinic owners and therapists. Clinic staff and other roles cannot open this inbox.",
  noClinicTitle: "Select an active clinic",
  noClinicBody: "Choose a clinic from the top bar. Tickets are loaded only for that active tenant.",
  refresh: "Refresh",
  safetyStrong: "Safety triage support only.",
  safetyBody:
    "Automated text detection can miss or misclassify symptoms. This inbox is not an emergency service; follow the clinic's direct-contact and emergency escalation protocol whenever serious symptoms are suspected.",
  loading: "Loading clinic tickets…",
  tryAgain: "Try again",
  emptyTitle: "No tickets for this clinic",
  emptyBody: "New patient messages will appear here and refresh automatically every 30 seconds.",
  summaryAria: "Inbox summary",
  open: "Open",
  unreadNeeds: "Unread / needs response",
  overdue: "Overdue >24h",
  filterAll: "All",
  filterActive: "Active",
  filterUnread: "Unread",
  updated: (time: string) => `Updated ${time} · polling every 30s`,
  noFilteredTitle: (filter: "all" | "open" | "unread") =>
    `No ${filter === "open" ? "active" : filter} tickets`,
  noFilteredBody: "Choose another filter to see the remaining clinic tickets.",
  listAria: "Ticket list",
  emergencyBadge: "Emergency text",
  urgentBadge: "Urgent text",
  unread: "Unread",
  opened: (time: string, age: string) => `Opened ${time} · latest patient activity ${age} ago`,
  emergencyStrong: "Emergency language detected.",
  emergencyBody:
    "This inbox is not an emergency service — این صندوق جای اورژانس نیست. Contact the patient immediately and follow the clinic's emergency protocol; do not wait for an inbox reply.",
  urgentStrong: "Urgent language detected.",
  urgentBody: "Review now, contact the patient and follow the clinic's same-day escalation pathway.",
  patientMessage: "Patient message",
  thread: "Reply thread",
  noReplies: "No replies yet.",
  saving: "Saving…",
  acknowledge: "Acknowledge review",
  replyLabel: "Reply as clinician",
  replyPlaceholder: "Write a clear, patient-safe response and document the next action…",
  savingReply: "Saving reply…",
  sendReply: "Send reply & mark answered",
  notAssigned:
    "Only the assigned therapist or clinic owner can reply to this patient. Ask the owner to update the assignment when needed.",
  closureLabel: "Closure note",
  closurePlaceholder: "Document contact, outcome and follow-up before closing…",
  closing: "Closing…",
  closeTicket: "Close ticket",
  closedAt: (time: string) => `Closed ${time}.`,
  answeredNote: "This ticket has a clinician response and is marked answered.",
};

export const ticketsText: PageText<typeof en> = {
  en,
  fa: {
    minutes: (n) => `${n.toLocaleString("fa-IR")} دقیقه`,
    hoursMinutes: (h, m) => `${h.toLocaleString("fa-IR")} ساعت و ${m.toLocaleString("fa-IR")} دقیقه`,
    daysHours: (d, h) => `${d.toLocaleString("fa-IR")} روز و ${h.toLocaleString("fa-IR")} ساعت`,
    unknownTime: "زمان نامشخص",
    slaEscalate: "همین حالا ارجاع دهید",
    slaAnswered: "پاسخ داده شده",
    slaWithin: "در محدوده هدف ۴ ساعته",
    slaDue: "زمان بررسی رسیده",
    slaOverdue: "تأخیر بیش از ۲۴ ساعت",
    senderClinician: "درمانگر",
    senderPatient: "بیمار",
    senderAi: "پیام خودکار دریافت",
    status: {
      open: "باز",
      acknowledged: "دیده‌شده",
      answered: "پاسخ داده شده",
      closed: "بسته",
    },
    refreshFailed:
      "به‌روزرسانی تیکت‌ها انجام نشد. اتصال را بررسی کنید و دوباره تلاش کنید؛ ردیف‌های نمایش‌داده‌شده ممکن است قدیمی باشند.",
    replyFailed:
      "پاسخ ذخیره نشد. متن شما هنوز اینجاست؛ تخصیص و اتصال را بررسی کنید و دوباره تلاش کنید.",
    replySaved: "پاسخ ذخیره شد و تیکت «پاسخ داده شده» علامت خورد.",
    ackFailed: "تأیید دیدن ذخیره نشد. دسترسی را بررسی کنید و دوباره تلاش کنید.",
    ackSaved: "دیدن تیکت با هویت احرازشده شما ثبت شد.",
    closeFailed:
      "تیکت بسته نشد. ابتدا هشدار بالینی مرتبط را رفع کنید و دوباره تلاش کنید؛ یادداشت شما هنوز اینجاست.",
    closeSaved: "تیکت با یادداشت بستن منتسب به شما بسته شد.",
    title: "پیام‌های بیماران",
    shortIntro: "پیام‌های بیمار که به بررسی درمانگر و پاسخ مستند نیاز دارند.",
    intro:
      "پیام‌های بیماران را بررسی کنید، عبارات حساس به زمان را تریاژ کنید و پاسخ‌ها را در رشته بالینی نگه دارید.",
    demoTitle: "صندوق نسخه نمایشی خالی است",
    demoBody:
      "حالت نمایشی پیام بیمار بارگذاری یا جعل نمی‌کند. برای استفاده از صندوق، پایگاه داده احرازشده کلینیک را متصل کنید.",
    accessTitle: "دسترسی بالینی لازم است",
    accessBody:
      "اطلاعات سلامت تیکت‌ها فقط برای مالک کلینیک و درمانگران در دسترس است. کارکنان کلینیک و سایر نقش‌ها نمی‌توانند این صندوق را باز کنند.",
    noClinicTitle: "یک کلینیک فعال انتخاب کنید",
    noClinicBody: "از نوار بالا کلینیک را انتخاب کنید. تیکت‌ها فقط برای همان کلینیک فعال بارگذاری می‌شوند.",
    refresh: "به‌روزرسانی",
    safetyStrong: "فقط پشتیبان تریاژ ایمنی.",
    safetyBody:
      "تشخیص خودکار متن ممکن است علائم را نبیند یا اشتباه طبقه‌بندی کند. این صندوق سرویس اورژانس نیست؛ هر زمان به علائم جدی مشکوک شدید، پروتکل تماس مستقیم و ارجاع اورژانسی کلینیک را دنبال کنید.",
    loading: "در حال بارگذاری تیکت‌های کلینیک…",
    tryAgain: "تلاش دوباره",
    emptyTitle: "تیکتی برای این کلینیک وجود ندارد",
    emptyBody: "پیام‌های جدید بیماران اینجا نمایش داده می‌شوند و هر ۳۰ ثانیه خودکار به‌روز می‌شوند.",
    summaryAria: "خلاصه صندوق",
    open: "باز",
    unreadNeeds: "خوانده‌نشده / نیازمند پاسخ",
    overdue: "تأخیر بیش از ۲۴ ساعت",
    filterAll: "همه",
    filterActive: "فعال",
    filterUnread: "خوانده‌نشده",
    updated: (time) => `به‌روزشده ${time} · بررسی هر ۳۰ ثانیه`,
    noFilteredTitle: (filter) =>
      filter === "open"
        ? "تیکت فعالی وجود ندارد"
        : filter === "unread"
          ? "تیکت خوانده‌نشده‌ای وجود ندارد"
          : "تیکتی وجود ندارد",
    noFilteredBody: "برای دیدن بقیه تیکت‌های کلینیک فیلتر دیگری انتخاب کنید.",
    listAria: "فهرست تیکت‌ها",
    emergencyBadge: "متن اورژانسی",
    urgentBadge: "متن فوری",
    unread: "خوانده‌نشده",
    opened: (time, age) => `ایجاد ${time} · آخرین فعالیت بیمار ${age} پیش`,
    emergencyStrong: "عبارت اورژانسی شناسایی شد.",
    emergencyBody:
      "این صندوق جای اورژانس نیست. فوراً با بیمار تماس بگیرید و پروتکل اورژانس کلینیک را دنبال کنید؛ منتظر پاسخ در صندوق نمانید.",
    urgentStrong: "عبارت فوری شناسایی شد.",
    urgentBody: "همین حالا بررسی کنید، با بیمار تماس بگیرید و مسیر ارجاع همان‌روز کلینیک را دنبال کنید.",
    patientMessage: "پیام بیمار",
    thread: "رشته پاسخ‌ها",
    noReplies: "هنوز پاسخی ثبت نشده است.",
    saving: "در حال ذخیره…",
    acknowledge: "ثبت دیدن و بررسی",
    replyLabel: "پاسخ به‌عنوان درمانگر",
    replyPlaceholder: "پاسخی روشن و ایمن برای بیمار بنویسید و اقدام بعدی را ثبت کنید…",
    savingReply: "در حال ذخیره پاسخ…",
    sendReply: "ارسال پاسخ و علامت «پاسخ داده شده»",
    notAssigned:
      "فقط درمانگر تخصیص‌یافته یا مالک کلینیک می‌تواند به این بیمار پاسخ دهد. در صورت نیاز از مالک بخواهید تخصیص را به‌روز کند.",
    closureLabel: "یادداشت بستن",
    closurePlaceholder: "پیش از بستن، تماس، نتیجه و پیگیری را ثبت کنید…",
    closing: "در حال بستن…",
    closeTicket: "بستن تیکت",
    closedAt: (time) => `بسته‌شده در ${time}.`,
    answeredNote: "درمانگر به این تیکت پاسخ داده و «پاسخ داده شده» علامت خورده است.",
  },
};
