import type { PageText } from "@/lib/i18n/text";

const en = {
  loadingCases: "Loading cases…",
  loadFailedTitle: "Cases could not be verified",
  loadFailedBody:
    "The clinical case list failed to load. No empty-state or assessment actions are shown until the authenticated database request succeeds.",
  retry: "Retry cases",
  title: "Examination & Reasoning",
  intro:
    "Structured findings rank provisional hypotheses transparently — decision support to verify independently, not a diagnosis or validated AI analysis.",
  caseLabel: "Patient case",
  selectCase: "Select a case…",
  unnamed: "Unnamed",
  noCaseTitle: "No case selected",
  noCaseBody: "Create a new patient case or pick a recent one to generate a clinical reasoning summary.",
  newCase: "New Assessment",
  safetyClear: "Structured safety screen is clear. Continue to monitor and verify throughout examination.",
  safetyAbsent: (disposition: string) =>
    `Safety clearance is absent (${disposition}). Resolve the documented pathway before treatment advice or patient education.`,
  dispositions: {
    "not-screened": "not screened",
    clear: "clear",
    "medical-review": "medical review",
    urgent: "urgent",
    emergency: "emergency",
  } as Record<string, string>,
  pain: (value: number) => `Pain ${value}/10`,
  planTreatment: "Plan treatment",
  handout: "Patient handout",
  locked: "Advice locked pending safety clearance",
  organising: "Organising clinical reasoning…",
  subjective: "Subjective Findings",
  objective: "Objective Findings (to examine)",
  hypotheses: "Possible Clinical Hypotheses",
  hypothesesFooter: "Template hypotheses only, not a diagnosis — confirm independently with examination.",
  differentials: "Differential Diagnosis Ideas",
  yellowFlags: "Yellow Flags (psychosocial)",
  redFlags: "Red Flags (safety)",
  redFlagsFooter: "Refer to physician / emergency care if clinically indicated.",
  missing: "Missing Information to Ask",
  tests: "Suggested Physical Tests",
  outcomes: "Suggested Outcome Measures",
  modules: "Body Region Modules",
  modulesHint: "Reference: conditions, tests, treatment ideas and education per region",
  browse: "Browse a region…",
  conditions: "Common conditions",
  questions: "Assessment questions",
  specialTests: "Special tests",
  functionalTests: "Functional tests",
  treatmentIdeas: "Treatment ideas",
  exercises: "Exercise suggestions",
  education: "Patient education points",
  selectRegion: "Select a region above to view its assessment and treatment reference.",
};

export const caseAnalysisText: PageText<typeof en> = {
  en,
  fa: {
    loadingCases: "در حال بارگذاری پرونده‌ها…",
    loadFailedTitle: "پرونده‌ها تأیید نشدند",
    loadFailedBody:
      "فهرست پرونده‌های بالینی بارگذاری نشد. تا موفقیت درخواست احراز هویت‌شده به دیتابیس، هیچ وضعیت خالی یا عملیات ارزیابی نمایش داده نمی‌شود.",
    retry: "بارگذاری دوباره پرونده‌ها",
    title: "معاینه و تحلیل",
    intro:
      "یافته‌های ساختاریافته، فرضیه‌های موقت را به‌طور شفاف رتبه‌بندی می‌کنند — پشتیبان تصمیم‌گیری برای تأیید مستقل، نه تشخیص یا تحلیل معتبر هوش مصنوعی.",
    caseLabel: "پرونده بیمار",
    selectCase: "انتخاب پرونده…",
    unnamed: "بدون نام",
    noCaseTitle: "پرونده‌ای انتخاب نشده",
    noCaseBody: "یک ارزیابی جدید ثبت کنید یا یکی از ارزیابی‌های اخیر را برای خلاصه استدلال بالینی انتخاب کنید.",
    newCase: "ارزیابی جدید",
    safetyClear: "غربالگری ایمنی ساختاریافته پاک است. در طول معاینه همچنان پایش و بررسی کنید.",
    safetyAbsent: (disposition) =>
      `مجوز ایمنی وجود ندارد (${disposition}). پیش از توصیه درمانی یا آموزش بیمار، مسیر ثبت‌شده را پیگیری کنید.`,
    dispositions: {
      "not-screened": "غربالگری نشده",
      clear: "پاک",
      "medical-review": "نیازمند بررسی پزشکی",
      urgent: "فوری",
      emergency: "اورژانسی",
    },
    pain: (value) => `درد ${value}/10`,
    planTreatment: "برنامه درمان",
    handout: "برگه آموزشی بیمار",
    locked: "توصیه‌ها تا مجوز ایمنی قفل است",
    organising: "در حال تنظیم استدلال بالینی…",
    subjective: "یافته‌های ذهنی (شرح حال)",
    objective: "یافته‌های عینی (برای معاینه)",
    hypotheses: "فرضیه‌های بالینی احتمالی",
    hypothesesFooter: "فقط فرضیه‌های الگو هستند، نه تشخیص — با معاینه مستقل تأیید کنید.",
    differentials: "ایده‌های تشخیص افتراقی",
    yellowFlags: "پرچم‌های زرد (روانی-اجتماعی)",
    redFlags: "پرچم‌های قرمز (ایمنی)",
    redFlagsFooter: "در صورت لزوم بالینی به پزشک یا اورژانس ارجاع دهید.",
    missing: "اطلاعاتی که باید پرسیده شود",
    tests: "تست‌های فیزیکی پیشنهادی",
    outcomes: "ابزارهای سنجش پیامد پیشنهادی",
    modules: "ماژول‌های نواحی بدن",
    modulesHint: "مرجع: بیماری‌ها، تست‌ها، ایده‌های درمانی و آموزش هر ناحیه",
    browse: "انتخاب ناحیه…",
    conditions: "بیماری‌های شایع",
    questions: "سؤالات ارزیابی",
    specialTests: "تست‌های اختصاصی",
    functionalTests: "تست‌های عملکردی",
    treatmentIdeas: "ایده‌های درمانی",
    exercises: "تمرین‌های پیشنهادی",
    education: "نکات آموزشی برای بیمار",
    selectRegion: "برای دیدن مرجع ارزیابی و درمان، یک ناحیه را از بالا انتخاب کنید.",
  },
};
