import type { PageText } from "@/lib/i18n/text";

const en = {
  title: "Patient Workspace",
  intro: "One view of this patient's assessments, safety, plan, home program, sessions and messages.",
  demoTitle: "Workspace needs the clinic database",
  demoBody:
    "Mock mode has no registered patients or episodes. Connect an authenticated clinic database to open a patient workspace.",
  accessTitle: "Clinical access required",
  accessBody: "Only clinic owners and assigned therapists can open a patient workspace.",
  noClinicTitle: "Select an active clinic",
  noClinicBody: "Choose a clinic from the top bar. The workspace loads only within that clinic.",
  noPatientTitle: "Choose a patient",
  noPatientBody: "Open a workspace from the patient registry.",
  toRegistry: "Patient registry",
  loadingPatient: "Loading patient…",
  patientFailed: "The patient could not be loaded. Check the connection and retry.",
  patientMissing:
    "This patient was not found in the active clinic, or you are not assigned to them.",
  retry: "Retry",
  sectionFailed: "Could not load this section. Nothing shown here should be read as empty.",
  loading: "Loading…",
  age: (age: number) => `${age} y`,
  noPhone: "No phone",
  activeEpisode: "Active episode",
  latestEpisode: "Latest episode",
  noEpisode: "No care episode",
  episodeStatus: {
    active: "active",
    paused: "paused",
    completed: "completed",
  } as Record<string, string>,
  since: (date: string) => `since ${date}`,
  therapists: "Therapists",
  unassigned: "Unassigned",
  newAssessment: "New assessment",
  sessionNotes: "Session notes",
  planner: "Treatment planner",
  inbox: "Patient messages",
  safetyTitle: "Safety",
  openAlerts: (count: number) =>
    `${count} unresolved clinical alert${count === 1 ? "" : "s"} — review before any treatment decision.`,
  noOpenAlerts: "No unresolved clinical alerts for this patient.",
  reviewAlerts: "Review alerts",
  latestScreen: "Latest assessment safety screen",
  dispositions: {
    clear: "clear",
    "medical-review": "medical review",
    urgent: "urgent",
    emergency: "emergency",
    "not-screened": "not screened",
  } as Record<string, string>,
  assessmentsTitle: "Assessments",
  assessmentsEmpty: "No assessment has been recorded for this patient yet.",
  casesFailed: "Assessments could not be loaded.",
  openAnalysis: "Open analysis",
  painOf: (value: number) => `pain ${value}/10`,
  planTitle: "Treatment plan",
  planEmpty: "No treatment plan has been drafted for the latest assessment.",
  planNoCase: "Record an assessment before planning treatment.",
  planStatus: {
    draft: "draft — awaiting clinician review",
    approved: "approved",
    rejected: "rejected",
    superseded: "superseded",
  } as Record<string, string>,
  version: (n: number) => `version ${n}`,
  programTitle: "Home program",
  programEmpty: "No exercise program has been published for this episode.",
  programStatus: {
    draft: "draft",
    published: "published",
    suspended: "suspended — safety review",
    revoked: "revoked",
  } as Record<string, string>,
  exercisesCount: (n: number) => `${n} exercise${n === 1 ? "" : "s"}`,
  reviewBy: (date: string) => `review by ${date}`,
  sessionsTitle: "Recent sessions",
  sessionsEmpty: "No signed session notes yet.",
  planLine: "Plan",
  outcomesTitle: "Outcome measures",
  outcomesEmpty: "No outcome measures recorded.",
  change: (from: number, to: number) => `${from} → ${to}`,
  improved: "improved",
  worsened: "worsened",
  unchanged: "unchanged",
  messagesTitle: "Messages",
  messagesEmpty: "No tickets from this patient.",
  openTickets: (n: number) => `${n} open`,
  ticketStatus: {
    open: "open",
    acknowledged: "acknowledged",
    answered: "answered",
    closed: "closed",
  } as Record<string, string>,
  pathwayTitle: "Care pathway",
  pathwaySubtitle: "Each step unlocks the next; the next step is highlighted.",
  stepAssessment: "Assessment",
  stepExam: "Examination & reasoning",
  stepPlan: "Treatment plan",
  stepProgram: "Home program",
  stepSessions: "Sessions",
  stateDone: "Done",
  stateNext: "Next step",
  stateTodo: "Not done yet",
  stateWaiting: "Awaiting your review",
  stateBlocked: "Needs attention",
  stateLocked: "After the previous step",
  stateUnknown: "Could not load",
  actStartAssessment: "Start assessment",
  actExam: "Record examination",
  actOpen: "Open",
  actPlan: "Build plan",
  actReviewPlan: "Review plan",
  actProgram: "Prescribe exercises",
  actNote: "Write session note",
  detailSafety: "Resolve the safety screen first",
  detailFindings: (n: number) => `Findings saved (version ${n})`,
  notesCount: (n: number) => `${n} signed note${n === 1 ? "" : "s"}`,
  provisional:
    "Everything here is a record of clinician work and provisional decision support — not a diagnosis or clearance.",
};

export const workspaceText: PageText<typeof en> = {
  en,
  fa: {
    title: "میز کار بیمار",
    intro: "نمای یکپارچه ارزیابی‌ها، ایمنی، برنامه درمان، برنامه خانگی، جلسات و پیام‌های این بیمار.",
    demoTitle: "میز کار به پایگاه داده کلینیک نیاز دارد",
    demoBody:
      "حالت نمایشی بیمار یا دوره درمان ثبت‌شده ندارد. برای باز کردن میز کار بیمار، پایگاه داده احرازشده کلینیک را متصل کنید.",
    accessTitle: "دسترسی بالینی لازم است",
    accessBody: "فقط مالک کلینیک و درمانگران تخصیص‌یافته می‌توانند میز کار بیمار را باز کنند.",
    noClinicTitle: "یک کلینیک فعال انتخاب کنید",
    noClinicBody: "از نوار بالا کلینیک را انتخاب کنید. میز کار فقط در همان کلینیک بارگذاری می‌شود.",
    noPatientTitle: "یک بیمار انتخاب کنید",
    noPatientBody: "میز کار را از فهرست بیماران باز کنید.",
    toRegistry: "فهرست بیماران",
    loadingPatient: "در حال بارگذاری بیمار…",
    patientFailed: "بیمار بارگذاری نشد. اتصال را بررسی کنید و دوباره تلاش کنید.",
    patientMissing: "این بیمار در کلینیک فعال پیدا نشد یا به شما تخصیص داده نشده است.",
    retry: "تلاش دوباره",
    sectionFailed: "این بخش بارگذاری نشد. خالی بودن آن را به معنای نبود داده تلقی نکنید.",
    loading: "در حال بارگذاری…",
    age: (age) => `${age.toLocaleString("fa-IR")} ساله`,
    noPhone: "بدون شماره",
    activeEpisode: "دوره درمان فعال",
    latestEpisode: "آخرین دوره درمان",
    noEpisode: "بدون دوره درمان",
    episodeStatus: {
      active: "فعال",
      paused: "متوقف",
      completed: "پایان‌یافته",
    },
    since: (date) => `از ${date}`,
    therapists: "درمانگران",
    unassigned: "بدون درمانگر",
    newAssessment: "ارزیابی جدید",
    sessionNotes: "یادداشت جلسات",
    planner: "برنامه‌ریز درمان",
    inbox: "پیام‌های بیماران",
    safetyTitle: "ایمنی",
    openAlerts: (count) =>
      `${count.toLocaleString("fa-IR")} هشدار بالینی رفع‌نشده — پیش از هر تصمیم درمانی بررسی کنید.`,
    noOpenAlerts: "هشدار بالینی رفع‌نشده‌ای برای این بیمار وجود ندارد.",
    reviewAlerts: "بررسی هشدارها",
    latestScreen: "غربالگری ایمنی آخرین ارزیابی",
    dispositions: {
      clear: "بدون مشکل",
      "medical-review": "نیازمند بررسی پزشکی",
      urgent: "فوری",
      emergency: "اورژانسی",
      "not-screened": "غربالگری‌نشده",
    },
    assessmentsTitle: "ارزیابی‌ها",
    assessmentsEmpty: "هنوز ارزیابی‌ای برای این بیمار ثبت نشده است.",
    casesFailed: "ارزیابی‌ها بارگذاری نشد.",
    openAnalysis: "باز کردن تحلیل",
    painOf: (value) => `درد ${value.toLocaleString("fa-IR")} از ۱۰`,
    planTitle: "برنامه درمان",
    planEmpty: "برای آخرین ارزیابی هنوز برنامه درمانی پیش‌نویس نشده است.",
    planNoCase: "پیش از برنامه‌ریزی درمان، یک ارزیابی ثبت کنید.",
    planStatus: {
      draft: "پیش‌نویس — در انتظار بررسی درمانگر",
      approved: "تأییدشده",
      rejected: "ردشده",
      superseded: "جایگزین‌شده",
    },
    version: (n) => `نسخه ${n.toLocaleString("fa-IR")}`,
    programTitle: "برنامه خانگی",
    programEmpty: "برای این دوره درمان برنامه تمرینی منتشر نشده است.",
    programStatus: {
      draft: "پیش‌نویس",
      published: "منتشرشده",
      suspended: "معلق — بررسی ایمنی",
      revoked: "لغوشده",
    },
    exercisesCount: (n) => `${n.toLocaleString("fa-IR")} تمرین`,
    reviewBy: (date) => `بازبینی تا ${date}`,
    sessionsTitle: "جلسات اخیر",
    sessionsEmpty: "هنوز یادداشت جلسه امضاشده‌ای وجود ندارد.",
    planLine: "برنامه",
    outcomesTitle: "ابزارهای سنجش پیامد",
    outcomesEmpty: "ابزار سنجش پیامدی ثبت نشده است.",
    change: (from, to) => `${from.toLocaleString("fa-IR")} ← ${to.toLocaleString("fa-IR")}`,
    improved: "بهبود",
    worsened: "بدتر",
    unchanged: "بدون تغییر",
    messagesTitle: "پیام‌ها",
    messagesEmpty: "تیکتی از این بیمار وجود ندارد.",
    openTickets: (n) => `${n.toLocaleString("fa-IR")} باز`,
    ticketStatus: {
      open: "باز",
      acknowledged: "دیده‌شده",
      answered: "پاسخ داده شده",
      closed: "بسته",
    },
    pathwayTitle: "مسیر درمان",
    pathwaySubtitle: "هر قدم، قدم بعدی را باز می‌کند؛ قدم بعدی برجسته شده است.",
    stepAssessment: "ارزیابی",
    stepExam: "معاینه و تحلیل",
    stepPlan: "برنامه درمان",
    stepProgram: "تمرین خانگی",
    stepSessions: "جلسات",
    stateDone: "انجام شد",
    stateNext: "قدم بعدی",
    stateTodo: "انجام نشده",
    stateWaiting: "در انتظار بررسی شما",
    stateBlocked: "نیاز به رسیدگی",
    stateLocked: "بعد از قدم قبل",
    stateUnknown: "بارگذاری نشد",
    actStartAssessment: "شروع ارزیابی",
    actExam: "ثبت معاینه",
    actOpen: "باز کردن",
    actPlan: "ساخت برنامه",
    actReviewPlan: "بررسی برنامه",
    actProgram: "تجویز تمرین",
    actNote: "نوشتن یادداشت جلسه",
    detailSafety: "ابتدا غربالگری ایمنی را رسیدگی کنید",
    detailFindings: (n) => `یافته‌ها ذخیره شده (نسخه ${n.toLocaleString("fa-IR")})`,
    notesCount: (n) => `${n.toLocaleString("fa-IR")} یادداشت امضاشده`,
    provisional:
      "همه موارد این صفحه سابقه کار درمانگر و پشتیبان تصمیم‌گیری موقت است — نه تشخیص و نه مجوز بالینی.",
  },
};
