import type { PageText } from "@/lib/i18n/text";

const en = {
  initial: "Initial intake",
  correction: "Correction",
  reassessment: "Reassessment",
  notRecorded: "Not recorded",
  title: "Signed assessment history",
  demoSubtitle: "Available for authenticated clinical records",
  demoBody:
    "This is a local demo case. It does not create signed clinical assessment versions, and corrections are intentionally disabled.",
  subtitle: "Append-only intake snapshots; corrections never overwrite the original",
  correctRecord: "Correct record",
  newReassessment: "New reassessment",
  loading: "Loading signed assessment history…",
  unverified: "Assessment history could not be verified. Editing is locked until the complete signed history loads.",
  retry: "Retry history",
  noVersion:
    "No signed assessment version was found. Editing is locked; ask an administrator to verify migration 020 and the case backfill.",
  reasonLength: "Document a reason between 3 and 1,000 characters.",
  reviewFields: "Review the required fields, age, region, and pain score.",
  mustChange: "A correction must change at least one assessment field.",
  invalidTime: "Enter a valid reassessment date and time.",
  notStored:
    "The revision was not stored. Refresh the history before retrying; another clinician may have created a newer version.",
  signed: (version: number) => `Assessment version ${version} was signed and stored.`,
  correctVersion: (version: number) => `Correct version ${version}`,
  reassessFrom: (version: number) => `Reassess from version ${version}`,
  immutable: (next: number) =>
    `The existing version remains immutable. Saving creates version ${next} and records your authenticated user ID.`,
  legacy:
    "This legacy snapshot contains a body-region or gender value outside the current controlled list. Review those fields explicitly before signing the new version; the original snapshot remains unchanged.",
  changeType: "Change type",
  correctionOption: "Correction to documentation",
  reassessmentOption: "New clinical reassessment",
  assessmentTime: "Assessment time",
  correctionTimeHint: "Corrections retain the original clinical assessment time.",
  reassessmentTimeHint: "Use the time the reassessment occurred.",
  reason: "Reason for this version",
  reasonHint: "Describe what was corrected or what prompted reassessment.",
  nameSnapshot: "Patient name snapshot",
  ageAtAssessment: "Age at assessment",
  genderSnapshot: "Gender snapshot",
  female: "Female",
  male: "Male",
  other: "Other",
  region: "Body region",
  mainComplaint: "Main complaint",
  painLocation: "Pain location",
  painIntensity: "Pain intensity (0–10)",
  duration: "Duration",
  mechanism: "Mechanism / onset",
  aggravating: "Aggravating factors",
  easing: "Easing factors",
  functional: "Functional limitations",
  goal: "Patient goal",
  medicalHistory: "Medical history",
  surgicalHistory: "Surgical history",
  imaging: "Imaging",
  medications: "Medications",
  cancel: "Cancel",
  signing: "Signing version…",
  sign: "Sign and append version",
  version: (version: number) => `Version ${version}`,
  current: "Current",
  assessed: (when: string) => `Assessed ${when}`,
  patientSnapshot: "Patient snapshot",
  ageGender: "Age / gender",
  regionShort: "Region",
  pain: "Pain",
  aggravatingShort: "Aggravating",
  easingShort: "Easing",
  recorded: (label: string, when: string) => `${label} recorded ${when}.`,
  author: (id: string) => `Authenticated clinician: ${id}`,
  legacyAuthor: "Legacy import: original actor was not available.",
  reasonLabel: (reason: string) => `Reason: ${reason}`,
};

export type CaseAssessmentText = typeof en;

export const caseAssessmentText: PageText<CaseAssessmentText> = {
  en,
  fa: {
    initial: "پذیرش اولیه",
    correction: "اصلاح",
    reassessment: "ارزیابی مجدد",
    notRecorded: "ثبت نشده",
    title: "تاریخچه امضاشده ارزیابی",
    demoSubtitle: "برای پرونده‌های بالینی احراز هویت‌شده در دسترس است",
    demoBody: "این یک کیس نمایشی محلی است. نسخه امضاشده ایجاد نمی‌کند و اصلاح عمداً غیرفعال است.",
    subtitle: "نسخه‌های پذیرش فقط افزوده می‌شوند؛ اصلاح هرگز نسخه اصلی را بازنویسی نمی‌کند",
    correctRecord: "اصلاح پرونده",
    newReassessment: "ارزیابی مجدد جدید",
    loading: "در حال بارگذاری تاریخچه امضاشده ارزیابی…",
    unverified: "تاریخچه ارزیابی تأیید نشد. تا بارگذاری کامل تاریخچه امضاشده، ویرایش قفل است.",
    retry: "بارگذاری دوباره تاریخچه",
    noVersion:
      "هیچ نسخه امضاشده‌ای پیدا نشد. ویرایش قفل است؛ از مدیر بخواهید migration 020 و انتقال داده‌های کیس را بررسی کند.",
    reasonLength: "دلیلی بین ۳ تا ۱۰۰۰ نویسه بنویسید.",
    reviewFields: "فیلدهای الزامی، سن، ناحیه و نمره درد را بررسی کنید.",
    mustChange: "اصلاح باید حداقل یکی از فیلدهای ارزیابی را تغییر دهد.",
    invalidTime: "تاریخ و ساعت معتبر ارزیابی مجدد را وارد کنید.",
    notStored:
      "نسخه جدید ذخیره نشد. پیش از تلاش دوباره تاریخچه را تازه کنید؛ ممکن است همکار دیگری نسخه جدیدتری ثبت کرده باشد.",
    signed: (version) => `نسخه ${version} ارزیابی امضا و ذخیره شد.`,
    correctVersion: (version) => `اصلاح نسخه ${version}`,
    reassessFrom: (version) => `ارزیابی مجدد از نسخه ${version}`,
    immutable: (next) => `نسخه فعلی تغییرناپذیر می‌ماند. ذخیره، نسخه ${next} را با شناسه کاربری شما ثبت می‌کند.`,
    legacy:
      "این نسخه قدیمی مقدار ناحیه بدن یا جنسیتی دارد که در فهرست فعلی نیست. پیش از امضای نسخه جدید آن فیلدها را صریحاً بازبینی کنید؛ نسخه اصلی بدون تغییر می‌ماند.",
    changeType: "نوع تغییر",
    correctionOption: "اصلاح مستندات",
    reassessmentOption: "ارزیابی مجدد بالینی جدید",
    assessmentTime: "زمان ارزیابی",
    correctionTimeHint: "اصلاح، زمان ارزیابی اصلی را حفظ می‌کند.",
    reassessmentTimeHint: "زمانی را وارد کنید که ارزیابی مجدد انجام شد.",
    reason: "دلیل این نسخه",
    reasonHint: "بنویسید چه چیزی اصلاح شد یا چه چیزی باعث ارزیابی مجدد شد.",
    nameSnapshot: "نام بیمار در این نسخه",
    ageAtAssessment: "سن هنگام ارزیابی",
    genderSnapshot: "جنسیت در این نسخه",
    female: "زن",
    male: "مرد",
    other: "سایر",
    region: "ناحیه بدن",
    mainComplaint: "شکایت اصلی",
    painLocation: "محل درد",
    painIntensity: "شدت درد (۰ تا ۱۰)",
    duration: "مدت",
    mechanism: "مکانیسم / نحوه شروع",
    aggravating: "عوامل تشدیدکننده",
    easing: "عوامل تسکین‌دهنده",
    functional: "محدودیت‌های عملکردی",
    goal: "هدف بیمار",
    medicalHistory: "سابقه پزشکی",
    surgicalHistory: "سابقه جراحی",
    imaging: "تصویربرداری",
    medications: "داروها",
    cancel: "انصراف",
    signing: "در حال امضای نسخه…",
    sign: "امضا و افزودن نسخه",
    version: (version) => `نسخه ${version}`,
    current: "فعلی",
    assessed: (when) => `ارزیابی ${when}`,
    patientSnapshot: "بیمار",
    ageGender: "سن / جنسیت",
    regionShort: "ناحیه",
    pain: "درد",
    aggravatingShort: "تشدیدکننده",
    easingShort: "تسکین‌دهنده",
    recorded: (label, when) => `${label} ثبت‌شده در ${when}.`,
    author: (id) => `فیزیوتراپیست احراز هویت‌شده: ${id}`,
    legacyAuthor: "انتقال داده قدیمی: ثبت‌کننده اصلی در دسترس نبود.",
    reasonLabel: (reason) => `دلیل: ${reason}`,
  },
};
