import type { PageText } from "@/lib/i18n/text";

const en = {
  historyFailed: "Prescription history could not be loaded.",
  errTargets: "Enter sets and repetitions per set, or total duration in seconds, for each exercise.",
  errTimezone: "Enter the patient's timezone.",
  errTimezoneInvalid: "Enter a valid timezone, for example Asia/Tehran.",
  errSafety: "The case safety screen is no longer clear.",
  errReviewDate: "Review date must be on or after the start date.",
  errEndDate: "End date must be on or after the start date.",
  errPrecautions: "Document precautions, or explicitly write that none are documented.",
  errStopRules: "Document patient-facing stop rules.",
  errCount: "A prescription must contain 1 to 20 exercises.",
  errExercise: "Select a patient-ready exercise for every row.",
  errDuplicate: "Do not prescribe an exercise twice.",
  errDosage: "Complete a valid dosage and weekly frequency for every exercise.",
  saveFailed:
    "Prescription draft was not saved. Confirm the treatment plan is still approved and the safety screen is clear.",
  publishBlocked:
    "Publish was blocked. Re-check current safety, treatment-plan approval and assignment. The existing patient program was not changed.",
  revokeFailed: "The published prescription was not revoked. Retry before advising the patient that it is stopped.",
  title: "Patient exercise prescription",
  subtitle:
    "Only exercises with complete Persian patient content are listed. Save a draft, then explicitly publish it to replace the current patient program.",
  timezone: "Patient timezone",
  timezoneHint: "Use the patient's local timezone, for example Asia/Tehran.",
  startDate: "Start date",
  endDate: "End date",
  reviewDate: "Review date",
  precautions: "Patient-facing precautions",
  precautionsHint: "Use explicit wording; do not leave this blank.",
  stopRules: "Stop rules",
  stopRulesHint: "When must the patient stop and contact the clinic or seek urgent care?",
  exercise: (n: number) => `Exercise ${n}`,
  select: "Select…",
  dosage: "Dosage shown to patient",
  target: "Target measurement",
  targetReps: "Sets and repetitions per set",
  targetDuration: "Total duration (seconds)",
  totalSeconds: "Total seconds",
  sets: "Sets",
  reps: "Repetitions per set",
  days: "Exercise days",
  weekdays: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  remove: (n: number) => `Remove exercise ${n}`,
  add: "Add exercise",
  versionStatus: (version: number, status: string) => `Prescription v${version} · ${status}`,
  unsaved: "Unsaved prescription",
  currentVersion: (version: number) => `Current patient version: ${version}`,
  saving: "Saving…",
  save: "Save prescription draft",
  publishAttest:
    "I verified each exercise, dosage, schedule, precaution, stop rule and review date against the patient record. Publishing will revoke the previous patient-visible version.",
  publishing: "Publishing…",
  publish: "Publish to patient portal",
  published: "This version is now patient-visible. The portal will load it on refresh.",
  loadingHistory: "Loading prescription history…",
  retry: "Retry",
  history: "Prescription history",
  version: (version: number) => `Version ${version}`,
  legacySchedule: "Legacy schedule",
  statuses: { draft: "draft", published: "published", revoked: "revoked", suspended: "suspended", superseded: "superseded" } as Record<string, string>,
  itemsAt: (count: number, when: string) => `${count} exercise(s) · ${when}`,
  openForReview: "Open for review",
  revokeAttest:
    "I intend to stop the current patient-visible prescription. The patient will have no active published program after revocation.",
  revoke: "Revoke current prescription",
};

export type PrescriptionText = typeof en;

export const prescriptionText: PageText<PrescriptionText> = {
  en,
  fa: {
    historyFailed: "تاریخچه نسخه‌های تمرین بارگذاری نشد.",
    errTargets: "برای هر تمرین تعداد ست و تکرار، یا مدت کل به ثانیه را وارد کنید.",
    errTimezone: "منطقه زمانی بیمار را وارد کنید.",
    errTimezoneInvalid: "منطقه زمانی معتبر وارد کنید، مثلاً Asia/Tehran.",
    errSafety: "غربالگری ایمنی پرونده دیگر پاک نیست.",
    errReviewDate: "تاریخ بازبینی باید هم‌زمان یا بعد از تاریخ شروع باشد.",
    errEndDate: "تاریخ پایان باید هم‌زمان یا بعد از تاریخ شروع باشد.",
    errPrecautions: "احتیاط‌ها را بنویسید، یا صریحاً بنویسید که احتیاطی ثبت نشده است.",
    errStopRules: "قوانین توقف تمرین برای بیمار را بنویسید.",
    errCount: "هر نسخه باید ۱ تا ۲۰ تمرین داشته باشد.",
    errExercise: "برای هر ردیف یک تمرین آماده برای بیمار انتخاب کنید.",
    errDuplicate: "یک تمرین را دو بار تجویز نکنید.",
    errDosage: "برای هر تمرین دوز و تعداد روز در هفته معتبر وارد کنید.",
    saveFailed: "پیش‌نویس نسخه ذخیره نشد. بررسی کنید برنامه درمان هنوز تأییدشده و غربالگری ایمنی پاک باشد.",
    publishBlocked:
      "انتشار انجام نشد. ایمنی فعلی، تأیید برنامه درمان و تخصیص بیمار را بررسی کنید. برنامه فعلی بیمار تغییری نکرد.",
    revokeFailed: "نسخه منتشرشده لغو نشد. پیش از اطلاع به بیمار دوباره تلاش کنید.",
    title: "نسخه تمرین بیمار",
    subtitle:
      "فقط تمرین‌هایی که محتوای فارسی کامل برای بیمار دارند نمایش داده می‌شوند. پیش‌نویس را ذخیره و سپس صریحاً منتشر کنید تا جایگزین برنامه فعلی بیمار شود.",
    timezone: "منطقه زمانی بیمار",
    timezoneHint: "منطقه زمانی محل زندگی بیمار، مثلاً Asia/Tehran.",
    startDate: "تاریخ شروع",
    endDate: "تاریخ پایان",
    reviewDate: "تاریخ بازبینی",
    precautions: "احتیاط‌ها برای بیمار",
    precautionsHint: "صریح بنویسید؛ خالی نگذارید.",
    stopRules: "قوانین توقف",
    stopRulesHint: "بیمار چه زمانی باید تمرین را متوقف و با کلینیک تماس بگیرد یا به اورژانس مراجعه کند؟",
    exercise: (n) => `تمرین ${n}`,
    select: "انتخاب…",
    dosage: "دوز نمایش‌داده‌شده به بیمار",
    target: "واحد هدف",
    targetReps: "ست و تکرار در هر ست",
    targetDuration: "مدت کل (ثانیه)",
    totalSeconds: "مجموع ثانیه",
    sets: "ست",
    reps: "تکرار در هر ست",
    days: "روزهای تمرین",
    weekdays: ["یکشنبه", "دوشنبه", "سه‌شنبه", "چهارشنبه", "پنجشنبه", "جمعه", "شنبه"],
    remove: (n) => `حذف تمرین ${n}`,
    add: "افزودن تمرین",
    versionStatus: (version, status) => `نسخه تمرین ${version} · ${status}`,
    unsaved: "نسخه ذخیره‌نشده",
    currentVersion: (version) => `نسخه فعلی بیمار: ${version}`,
    saving: "در حال ذخیره…",
    save: "ذخیره پیش‌نویس نسخه",
    publishAttest:
      "هر تمرین، دوز، برنامه زمانی، احتیاط، قانون توقف و تاریخ بازبینی را با پرونده بیمار تطبیق دادم. انتشار، نسخه قبلیِ قابل مشاهده برای بیمار را لغو می‌کند.",
    publishing: "در حال انتشار…",
    publish: "انتشار در پرتال بیمار",
    published: "این نسخه اکنون برای بیمار قابل مشاهده است و با تازه‌سازی پرتال بارگذاری می‌شود.",
    loadingHistory: "در حال بارگذاری تاریخچه نسخه‌ها…",
    retry: "تلاش دوباره",
    history: "تاریخچه نسخه‌های تمرین",
    version: (version) => `نسخه ${version}`,
    legacySchedule: "زمان‌بندی قدیمی",
    statuses: { draft: "پیش‌نویس", published: "منتشرشده", revoked: "لغوشده", suspended: "معلق", superseded: "جایگزین‌شده" },
    itemsAt: (count, when) => `${count} تمرین · ${when}`,
    openForReview: "باز کردن برای بازبینی",
    revokeAttest:
      "قصد دارم نسخه فعلیِ قابل مشاهده برای بیمار را متوقف کنم. پس از لغو، بیمار برنامه منتشرشده فعالی نخواهد داشت.",
    revoke: "لغو نسخه فعلی",
  },
};
