import type { PageText } from "@/lib/i18n/text";

const en = {
  stages: {
    acute: "Acute",
    subacute: "Subacute",
    chronic: "Chronic",
    "post-op": "Post-operative",
    "return-to-sport": "Return to sport",
  } as Record<string, string>,
  sections: {
    manualTherapy: "Manual therapy",
    exerciseTherapy: "Exercise therapy",
    mobility: "Mobility",
    strengthening: "Strengthening",
    motorControl: "Motor control",
    balance: "Balance and proprioception",
    education: "Education",
    homeProgram: "Home exercise program",
    progression: "Progression rules",
  } as Record<string, string>,
  statuses: {
    draft: "draft",
    approved: "approved",
    rejected: "rejected",
    superseded: "superseded",
  } as Record<string, string>,
  dispositions: {
    "not-screened": "not screened",
    clear: "clear",
    "medical-review": "medical review",
    urgent: "urgent",
    emergency: "emergency",
  } as Record<string, string>,
  loading: "Loading…",
  switchConfirm: "Switch patient cases and discard the unsaved treatment-plan work on this screen?",
  historyFailed: "Saved plan history could not be loaded. Check the connection and retry.",
  needCase: "Select a patient case with a completed structured safety screen before planning treatment.",
  blocked:
    "Treatment planning is blocked until the active case has a completed, clear safety screen and all concerns are resolved.",
  needRegion: "Select a body region first.",
  postOpMissing:
    "For post-operative planning, enter the procedure, surgery date, precautions and weight-bearing status. Use an explicit value such as “none documented” rather than leaving a field blank.",
  futureSurgery: "Surgery date cannot be in the future.",
  confirmProtocol: "Confirm that the operating team's protocol and restrictions were reviewed.",
  incomplete: "The plan parameters are incomplete.",
  generateFailed: "The treatment plan could not be generated safely.",
  saveRequirements:
    "A linked case, editable unsaved draft, and current clear safety screen are required before saving.",
  sectionsInvalid:
    "Complete every required plan section, keep one item per line and remove blank or oversized items before saving.",
  saveFailed:
    "The draft was not saved. Re-check assignment, safety status and connection; the generated text remains on this screen.",
  openConfirm: "Discard the unsaved treatment-plan work on this screen and open the saved draft?",
  confirmReview:
    "Confirm that you reviewed the original case, current safety screen and every plan item before signing.",
  approvalBlocked: "Approval is blocked because the current case safety screen is no longer clear.",
  reviewFailed:
    "The review decision was not stored. The draft remains unsigned. Refresh the case safety status and retry.",
  title: "Treatment Plan Builder",
  intro:
    "Generate a draft only after the active case has a completed, clear safety screen. Every input change invalidates the previous draft.",
  caseAria: "Patient case for treatment planning",
  selectCase: "Select a case…",
  unnamed: "Unnamed",
  loadError: "Patient cases could not be loaded securely. Treatment planning is locked; this is not an empty case list.",
  retryCases: "Retry case list",
  gatePassed: "Safety gate passed for this case",
  gateLocked: "Treatment planning locked",
  screenCompleted: (when: string) =>
    `Structured screen completed ${when}. Continue clinical monitoring; this is not a diagnosis or blanket clearance.`,
  statusUnavailable: "Case and safety status are unavailable. Retry the case list before planning treatment.",
  currentDisposition: (value: string) =>
    `Current safety disposition: ${value}. Resolve and document the appropriate escalation before generating advice.`,
  selectOrCreate:
    "Select or create a case and complete its structured red-flag screen first. Manual planning without a case is disabled.",
  parameters: "Plan Parameters",
  prefilled: (name: string) => `Pre-filled from case: ${name}`,
  noCase: "No active case — treatment planning is disabled",
  region: "Body region",
  select: "Select…",
  stage: "Stage",
  irritability: "Irritability",
  low: "Low",
  moderate: "Moderate",
  high: "High",
  painSeverity: (value: number) => `Pain severity — ${value}/10`,
  impairment: "Main impairment",
  impairmentPlaceholder: "e.g. Hip abductor weakness",
  goal: "Patient goal",
  goalPlaceholder: "e.g. Return to running 5km",
  postOpTitle: "Required post-operative protocol details",
  postOpBody:
    "The planner cannot infer restrictions from the operation name. Enter the operating team's documented instructions.",
  procedure: "Procedure",
  procedurePlaceholder: "e.g. Right rotator-cuff repair",
  surgeryDate: "Surgery date",
  weightBearing: "Weight-bearing / loading status",
  weightBearingPlaceholder: "e.g. NWB, WBAT, or upper-limb loading restriction",
  precautions: "Precautions and prohibited movements",
  precautionsHint: "Enter “none documented” only after checking the protocol.",
  precautionsPlaceholder: "Document range, load, wound or tissue-healing restrictions",
  protocolAttest: "I reviewed the current operating-team protocol, precautions and loading status for this patient.",
  generating: "Generating…",
  generate: "Generate treatment plan",
  building: "Building a stage-appropriate plan…",
  planFor: (region: string, stage: string) => `Plan for ${region} — ${stage}`,
  edited: "Clinician-edited draft",
  editTitle: "Edit clinical draft",
  editSubtitle:
    "Review and edit the generated template before saving. Use one item per line; the exact edited structure is stored in the new version.",
  immutable:
    "This saved version is immutable. Generate again to create and edit a new version instead of rewriting the audit trail.",
  frequency: "Recommended frequency",
  sectionHint: "One item per line; maximum 12 items.",
  recordTitle: "Clinical record and sign-off",
  recordSubtitle:
    "Generation never publishes a plan. Save a versioned draft, re-check the source record, then explicitly approve or reject it.",
  demo: "Demo mode: this sample is not a clinical record and cannot be signed or published.",
  legacy: "This legacy case is not linked to a patient and care episode. Link or archive it before saving a plan.",
  versionStatus: (version: number, status: string) => `Version ${version} · ${status}`,
  unsaved: "Unsaved generated draft",
  serverTime: (when: string) => `Server timestamp: ${when}`,
  saving: "Saving…",
  saveDraft: "Save versioned draft",
  reviewNote: "Review note",
  reviewNoteHint: "Optional for approval; record the reason when rejecting or changing clinical direction.",
  reviewAttest:
    "I reviewed the original patient record, current safety screen, missing information, precautions and every item in this draft. I take clinical responsibility for this sign-off.",
  savingDecision: "Saving decision…",
  approve: "Approve and sign",
  reject: "Reject draft",
  finalStatus: (status: string) =>
    `This version is ${status}. A new generation must be saved as a new version; signed records are never edited in place.`,
  historyTitle: "Plan version history",
  historySubtitle: "Append-only drafts and clinician review decisions for the active case.",
  loadingPlans: "Loading saved plans…",
  retry: "Retry",
  noPlans: "No saved treatment-plan versions for this case.",
  version: (version: number) => `Version ${version}`,
  openForReview: "Open for review",
};

export type PlannerText = typeof en;

export const plannerText: PageText<PlannerText> = {
  en,
  fa: {
    stages: {
      acute: "حاد",
      subacute: "تحت‌حاد",
      chronic: "مزمن",
      "post-op": "پس از جراحی",
      "return-to-sport": "بازگشت به ورزش",
    },
    sections: {
      manualTherapy: "درمان دستی",
      exerciseTherapy: "تمرین‌درمانی",
      mobility: "تحرک",
      strengthening: "تقویت",
      motorControl: "کنترل حرکتی",
      balance: "تعادل و حس عمقی",
      education: "آموزش",
      homeProgram: "برنامه تمرین خانگی",
      progression: "قوانین پیشرفت",
    },
    statuses: {
      draft: "پیش‌نویس",
      approved: "تأییدشده",
      rejected: "ردشده",
      superseded: "جایگزین‌شده",
    },
    dispositions: {
      "not-screened": "غربالگری نشده",
      clear: "پاک",
      "medical-review": "نیازمند بررسی پزشکی",
      urgent: "فوری",
      emergency: "اورژانسی",
    },
    loading: "در حال بارگذاری…",
    switchConfirm: "پرونده عوض شود و کار ذخیره‌نشده برنامه درمان در این صفحه از بین برود؟",
    historyFailed: "تاریخچه برنامه‌های ذخیره‌شده بارگذاری نشد. اتصال را بررسی و دوباره تلاش کنید.",
    needCase: "پیش از برنامه‌ریزی درمان، پرونده‌ای با غربالگری ایمنی کامل‌شده انتخاب کنید.",
    blocked: "تا وقتی غربالگری ایمنی پرونده فعال کامل و پاک نباشد و همه نگرانی‌ها برطرف نشده باشد، برنامه‌ریزی درمان قفل است.",
    needRegion: "ابتدا ناحیه بدن را انتخاب کنید.",
    postOpMissing:
      "برای برنامه پس از جراحی، نوع جراحی، تاریخ جراحی، احتیاط‌ها و وضعیت تحمل وزن را وارد کنید. به‌جای خالی گذاشتن، مقدار صریحی مثل «ثبت نشده» بنویسید.",
    futureSurgery: "تاریخ جراحی نمی‌تواند در آینده باشد.",
    confirmProtocol: "تأیید کنید پروتکل و محدودیت‌های تیم جراحی را بررسی کرده‌اید.",
    incomplete: "پارامترهای برنامه ناقص است.",
    generateFailed: "برنامه درمان به‌طور امن ساخته نشد.",
    saveRequirements: "برای ذخیره، پرونده متصل، پیش‌نویس ذخیره‌نشده و غربالگری ایمنی پاکِ فعلی لازم است.",
    sectionsInvalid:
      "همه بخش‌های الزامی برنامه را کامل کنید، هر مورد را در یک خط بنویسید و موارد خالی یا خیلی طولانی را حذف کنید.",
    saveFailed:
      "پیش‌نویس ذخیره نشد. تخصیص بیمار، وضعیت ایمنی و اتصال را بررسی کنید؛ متن تولیدشده روی صفحه باقی است.",
    openConfirm: "کار ذخیره‌نشده این صفحه حذف و پیش‌نویس ذخیره‌شده باز شود؟",
    confirmReview: "تأیید کنید پیش از امضا، پرونده اصلی، غربالگری ایمنی فعلی و همه موارد برنامه را بررسی کرده‌اید.",
    approvalBlocked: "تأیید ممکن نیست، چون غربالگری ایمنی پرونده دیگر پاک نیست.",
    reviewFailed: "تصمیم بازبینی ذخیره نشد و پیش‌نویس امضا نشده باقی ماند. وضعیت ایمنی را تازه کنید و دوباره تلاش کنید.",
    title: "برنامه‌ریز درمان",
    intro:
      "پیش‌نویس را فقط پس از کامل و پاک بودن غربالگری ایمنی پرونده بسازید. هر تغییر در ورودی‌ها پیش‌نویس قبلی را باطل می‌کند.",
    caseAria: "پرونده بیمار برای برنامه‌ریزی درمان",
    selectCase: "انتخاب پرونده…",
    unnamed: "بدون نام",
    loadError: "پرونده‌ها به‌طور امن بارگذاری نشد. برنامه‌ریزی درمان قفل است؛ این به معنای خالی بودن فهرست نیست.",
    retryCases: "بارگذاری دوباره پرونده‌ها",
    gatePassed: "دروازه ایمنی برای این پرونده رد شد",
    gateLocked: "برنامه‌ریزی درمان قفل است",
    screenCompleted: (when) =>
      `غربالگری ساختاریافته در ${when} کامل شد. پایش بالینی را ادامه دهید؛ این تشخیص یا مجوز کلی نیست.`,
    statusUnavailable: "وضعیت پرونده و ایمنی در دسترس نیست. پیش از برنامه‌ریزی، فهرست پرونده‌ها را دوباره بارگذاری کنید.",
    currentDisposition: (value) =>
      `وضعیت ایمنی فعلی: ${value}. پیش از ارائه توصیه، ارجاع مناسب را انجام و ثبت کنید.`,
    selectOrCreate:
      "یک پرونده انتخاب یا ایجاد کنید و ابتدا غربالگری پرچم قرمز آن را کامل کنید. برنامه‌ریزی دستی بدون پرونده غیرفعال است.",
    parameters: "پارامترهای برنامه",
    prefilled: (name) => `پرشده از پرونده: ${name}`,
    noCase: "پرونده فعالی نیست — برنامه‌ریزی درمان غیرفعال است",
    region: "ناحیه بدن",
    select: "انتخاب…",
    stage: "مرحله",
    irritability: "تحریک‌پذیری",
    low: "کم",
    moderate: "متوسط",
    high: "زیاد",
    painSeverity: (value) => `شدت درد — ${value} از ۱۰`,
    impairment: "نقص اصلی",
    impairmentPlaceholder: "مثلاً ضعف ابداکتورهای ران",
    goal: "هدف بیمار",
    goalPlaceholder: "مثلاً بازگشت به دویدن ۵ کیلومتر",
    postOpTitle: "جزئیات الزامی پروتکل پس از جراحی",
    postOpBody: "برنامه‌ریز نمی‌تواند محدودیت‌ها را از نام جراحی حدس بزند. دستورالعمل ثبت‌شده تیم جراحی را وارد کنید.",
    procedure: "نوع جراحی",
    procedurePlaceholder: "مثلاً ترمیم روتاتور کاف راست",
    surgeryDate: "تاریخ جراحی",
    weightBearing: "وضعیت تحمل وزن / بارگذاری",
    weightBearingPlaceholder: "مثلاً NWB، WBAT یا محدودیت بارگذاری اندام فوقانی",
    precautions: "احتیاط‌ها و حرکات ممنوع",
    precautionsHint: "«ثبت نشده» را فقط پس از بررسی پروتکل وارد کنید.",
    precautionsPlaceholder: "محدودیت‌های دامنه، بار، زخم یا ترمیم بافت را ثبت کنید",
    protocolAttest: "پروتکل فعلی تیم جراحی، احتیاط‌ها و وضعیت بارگذاری این بیمار را بررسی کردم.",
    generating: "در حال ساخت…",
    generate: "ساخت برنامه درمان",
    building: "در حال ساخت برنامه متناسب با مرحله…",
    planFor: (region, stage) => `برنامه برای ${region} — ${stage}`,
    edited: "پیش‌نویس ویرایش‌شده توسط درمانگر",
    editTitle: "ویرایش پیش‌نویس بالینی",
    editSubtitle:
      "الگوی تولیدشده را پیش از ذخیره بازبینی و ویرایش کنید. هر مورد در یک خط؛ ساختار دقیق ویرایش‌شده در نسخه جدید ذخیره می‌شود.",
    immutable: "این نسخه ذخیره‌شده تغییرناپذیر است. برای ویرایش، دوباره بسازید تا نسخه جدیدی ایجاد شود.",
    frequency: "تواتر پیشنهادی",
    sectionHint: "هر مورد در یک خط؛ حداکثر ۱۲ مورد.",
    recordTitle: "ثبت در پرونده و امضا",
    recordSubtitle:
      "ساخت برنامه هرگز آن را منتشر نمی‌کند. پیش‌نویس نسخه‌دار را ذخیره کنید، پرونده اصلی را دوباره بررسی و سپس صریحاً تأیید یا رد کنید.",
    demo: "حالت نمایشی: این نمونه پرونده بالینی نیست و قابل امضا یا انتشار نیست.",
    legacy: "این پرونده قدیمی به بیمار و دوره درمان متصل نیست. پیش از ذخیره برنامه، آن را متصل یا بایگانی کنید.",
    versionStatus: (version, status) => `نسخه ${version} · ${status}`,
    unsaved: "پیش‌نویس تولیدشده ذخیره‌نشده",
    serverTime: (when) => `زمان ثبت در سرور: ${when}`,
    saving: "در حال ذخیره…",
    saveDraft: "ذخیره پیش‌نویس نسخه‌دار",
    reviewNote: "یادداشت بازبینی",
    reviewNoteHint: "برای تأیید اختیاری است؛ هنگام رد یا تغییر مسیر بالینی، دلیل را بنویسید.",
    reviewAttest:
      "پرونده اصلی بیمار، غربالگری ایمنی فعلی، اطلاعات ناقص، احتیاط‌ها و همه موارد این پیش‌نویس را بررسی کردم و مسئولیت بالینی این امضا را می‌پذیرم.",
    savingDecision: "در حال ثبت تصمیم…",
    approve: "تأیید و امضا",
    reject: "رد پیش‌نویس",
    finalStatus: (status) =>
      `وضعیت این نسخه: ${status}. برنامه جدید باید به‌صورت نسخه جدید ذخیره شود؛ پرونده امضاشده هرگز ویرایش نمی‌شود.`,
    historyTitle: "تاریخچه نسخه‌های برنامه",
    historySubtitle: "پیش‌نویس‌ها و تصمیمات بازبینی درمانگر برای پرونده فعال (فقط افزودنی).",
    loadingPlans: "در حال بارگذاری برنامه‌های ذخیره‌شده…",
    retry: "تلاش دوباره",
    noPlans: "هنوز نسخه‌ای از برنامه درمان برای این پرونده ذخیره نشده است.",
    version: (version) => `نسخه ${version}`,
    openForReview: "باز کردن برای بازبینی",
  },
};
