import type { PageText } from "@/lib/i18n/text";

const en = {
  title: "Settings",
  introDemo: "Browser-only preferences for the explicit demo environment.",
  introReal: "Authenticated account context and non-clinical browser preferences.",
  profileTitle: "Profile & Preferences",
  demoClinic: "Demo clinic name",
  demoClinicPlaceholder: "e.g. City Physio Clinic",
  demoTherapist: "Demo therapist name",
  demoTherapistPlaceholder: "e.g. Dr. Omidvary",
  profile: "Authenticated profile",
  role: "Role",
  roles: {
    clinic_owner: "Clinic owner",
    therapist: "Therapist",
    clinic_staff: "Clinic staff",
    patient: "Patient",
    platform_admin: "Platform administrator",
  } as Record<string, string>,
  unavailable: "Unavailable",
  activeClinic: "Active clinic",
  noClinic: "No clinic selected",
  units: "Units",
  metric: "Metric (kg, cm)",
  imperial: "Imperial (lb, in)",
  saved: "Saved!",
  save: "Save browser preferences",
  dbTitle: "Supabase Connection",
  dbSubtitle: "Cloud database for cases, patients and tickets",
  configError: "Configuration error — cloud mode is unavailable",
  demoMode: "Explicit demo mode — no cloud writes",
  cloudLoaded: "Cloud configuration loaded",
  cloudUnavailable: "Cloud configuration unavailable",
  dbDemoBody:
    "Demo data stays in this browser and is never represented as a cloud save. To test real authentication and RLS, copy ",
  dbRealBody:
    "Clinical records on this screen are not stored in browser preferences. Deployment configuration comes from ",
  configFile: "configuration file ",
  andMigrations: "and migrations in",
  migrationRunner: "through the tracked migration runner. See the Persian setup guide in",
  aiTitle: "AI Connection",
  aiSubtitle: "Audited clinical-draft capability",
  aiEnabled:
    "The browser gate for audited clinical drafts is enabled. Server approval, provider configuration, quota reservation, stored-case safety and clinician review are still verified on every request; this indicator does not prove provider availability.",
  aiDisabled:
    "Audited clinical drafts are disabled in this deployment. Deterministic templates are not represented as a connected diagnostic AI service.",
  aiKey: "AI API key",
  aiKeyPlaceholder: "Configure via server environment variables — never in the browser",
  localTitle: "Local Data",
  localSubtitle: "Cases are stored only in this browser",
  localBody:
    "Clearing local data removes all saved cases and preferences from this browser and restores the sample cases. This cannot be undone.",
  cleared: "Cleared…",
  clear: "Clear local data",
};

export const settingsText: PageText<typeof en> = {
  en,
  fa: {
    title: "تنظیمات",
    introDemo: "تنظیمات فقط-مرورگر برای محیط نمایشی.",
    introReal: "اطلاعات حساب احرازشده و تنظیمات غیربالینی مرورگر.",
    profileTitle: "پروفایل و ترجیحات",
    demoClinic: "نام کلینیک نمایشی",
    demoClinicPlaceholder: "مثلاً کلینیک فیزیوتراپی شهر",
    demoTherapist: "نام درمانگر نمایشی",
    demoTherapistPlaceholder: "مثلاً دکتر امیدواری",
    profile: "پروفایل احرازشده",
    role: "نقش",
    roles: {
      clinic_owner: "مالک کلینیک",
      therapist: "درمانگر",
      clinic_staff: "کارمند کلینیک",
      patient: "بیمار",
      platform_admin: "مدیر سامانه",
    },
    unavailable: "در دسترس نیست",
    activeClinic: "کلینیک فعال",
    noClinic: "کلینیکی انتخاب نشده",
    units: "واحدها",
    metric: "متریک (کیلوگرم، سانتی‌متر)",
    imperial: "امپریال (پوند، اینچ)",
    saved: "ذخیره شد!",
    save: "ذخیره ترجیحات مرورگر",
    dbTitle: "اتصال Supabase",
    dbSubtitle: "پایگاه داده ابری برای موارد، بیماران و تیکت‌ها",
    configError: "خطای پیکربندی — حالت ابری در دسترس نیست",
    demoMode: "حالت نمایشی — بدون ذخیره ابری",
    cloudLoaded: "پیکربندی ابری بارگذاری شد",
    cloudUnavailable: "پیکربندی ابری در دسترس نیست",
    dbDemoBody:
      "داده‌های نمایشی فقط در همین مرورگر می‌مانند و هرگز ذخیره ابری نشان داده نمی‌شوند. برای آزمودن احراز هویت واقعی و RLS، این فایل را کپی کنید: ",
    dbRealBody:
      "سوابق بالینی این صفحه در ترجیحات مرورگر ذخیره نمی‌شوند. پیکربندی استقرار از این فایل می‌آید: ",
    configFile: "فایل پیکربندی ",
    andMigrations: "و مهاجرت‌های پوشه",
    migrationRunner: "از طریق اجراکننده ثبت‌شده مهاجرت. راهنمای فارسی راه‌اندازی:",
    aiTitle: "اتصال هوش مصنوعی",
    aiSubtitle: "قابلیت پیش‌نویس بالینی ممیزی‌شده",
    aiEnabled:
      "دروازه مرورگر برای پیش‌نویس‌های بالینی ممیزی‌شده فعال است. تأیید سرور، پیکربندی ارائه‌دهنده، رزرو سهمیه، ایمنی مورد ذخیره‌شده و بررسی درمانگر همچنان در هر درخواست بررسی می‌شوند؛ این نشانگر در دسترس بودن ارائه‌دهنده را ثابت نمی‌کند.",
    aiDisabled:
      "پیش‌نویس‌های بالینی ممیزی‌شده در این استقرار غیرفعال است. الگوهای قطعی به‌عنوان سرویس تشخیصی هوش مصنوعی متصل معرفی نمی‌شوند.",
    aiKey: "کلید API هوش مصنوعی",
    aiKeyPlaceholder: "از طریق متغیرهای محیطی سرور تنظیم کنید — هرگز در مرورگر",
    localTitle: "داده‌های محلی",
    localSubtitle: "موارد فقط در همین مرورگر ذخیره می‌شوند",
    localBody:
      "پاک کردن داده‌های محلی همه موارد و ترجیحات ذخیره‌شده را از این مرورگر حذف می‌کند و موارد نمونه را برمی‌گرداند. این کار برگشت‌پذیر نیست.",
    cleared: "پاک شد…",
    clear: "پاک کردن داده‌های محلی",
  },
};
