import type { PageText } from "@/lib/i18n/text";

const en = {
  title: "Patient Registry",
  introShort: "Clinic-scoped patients, active care episodes and therapist assignments.",
  intro: "Find patients in the active clinic, review current care and start a new episode safely.",
  demoEmpty: "Demo registry is empty",
  demoEmptyHint:
    "Mock mode does not fabricate patient health information. Connect an authenticated clinic database to use the registry.",
  checkingAccess: "Checking clinical access…",
  accessRequired: "Clinical access required",
  accessRequiredHint:
    "Patient PHI is available only to clinic owners and therapists. Clinic staff and other roles cannot open this registry.",
  selectClinic: "Select an active clinic",
  selectClinicHint: "Choose a clinic from the top bar. Patient records are loaded only for that active tenant.",
  closeForm: "Close form",
  newPatient: "New patient",
  createTitle: "Create patient and first care episode",
  createSubtitle: "Saved as one database transaction; no partial patient record is created.",
  fullName: "Full name",
  phoneOptional: "Phone (optional)",
  phoneHint: "7–15 digits; Persian and Arabic numerals are accepted.",
  birthYearOptional: "Birth year (optional)",
  birthYearHint: "Solar Hijri (e.g. 1365) or Gregorian (e.g. 1986)",
  genderOptional: "Gender (optional)",
  notRecorded: "Not recorded",
  female: "Female",
  male: "Male",
  other: "Other",
  episodeTitle: "Care episode title (Persian)",
  weeklyTarget: "Weekly target",
  weeklyTargetHint: "Planned sessions or home-program days per week (1–7).",
  therapistAutoAssign: "You will be assigned as this patient’s therapist automatically.",
  ownerUnassigned: "The new patient will start unassigned; an owner can assign a therapist later.",
  creating: "Creating…",
  createButton: "Create patient & episode",
  createFailed:
    "Patient was not created. Check your connection and permissions, and confirm the create_patient_episode RPC is deployed.",
  created: "Patient and active care episode were created atomically.",
  errName2: "Enter at least 2 characters.",
  errName120: "Name must be 120 characters or fewer.",
  errPhone: "Use 7 to 15 digits, optionally starting with +.",
  errBirthYear: (max: number) => `Use a year from 1900 to ${max} (or Solar Hijri 1279–${max - 621}).`,
  errTitle2: "Enter at least 2 characters.",
  errTitle160: "Episode title must be 160 characters or fewer.",
  errWeekly: "Weekly target must be a whole number from 1 to 7.",
  searchLabel: "Search patient name",
  searchPlaceholder: "Search by patient name…",
  search: "Search",
  clear: "Clear",
  refresh: "Refresh",
  loadingPatients: "Loading clinic patients…",
  loadFailed: "Patient registry could not be loaded. Check the connection and clinic permissions, then retry.",
  tryAgain: "Try again",
  noMatches: "No matching patients",
  noPatients: "No patients in this clinic",
  noMatchesHint: "Try a different name or clear the search.",
  noPatientsHint: "Create the first patient and active care episode when the clinic is ready.",
  clearSearch: "Clear search",
  caption: "Patients in the active clinic with active episode and therapist assignment",
  colPatient: "Patient",
  colDemographics: "Demographics",
  colEpisode: "Active care episode",
  colTherapist: "Assigned therapist",
  colAdded: "Added",
  colActions: "Actions",
  noPhone: "No phone recorded",
  born: (year: number, age: number) => `Born ${year} · approx. ${age} years`,
  noBirthYear: "Birth year not recorded",
  targetSince: (target: number, since: string) => `Target ${target}/week · since ${since}`,
  noActiveEpisode: "No active episode",
  unassigned: "Unassigned",
  manage: "Manage",
  workspace: "Workspace",
  showing: (first: number, last: number, total: number) => `Showing ${first}–${last} of ${total}`,
  previous: "Previous",
  next: "Next",
  previousAria: "Previous patient page",
  nextAria: "Next patient page",
  pageOf: (page: number, total: number) => `Page ${page} of ${total}`,
  unknownDate: "Unknown",
  manageTitle: (name: string) => `Manage ${name}`,
  manageSubtitle: "All lifecycle and portal changes are authorized and stamped by the database.",
  close: "Close",
  changeRejected: "The change was rejected. Check permissions, current episode state and database migration 015.",
  demographics: "Demographics",
  phone: "Phone",
  birthYear: "Birth year",
  gender: "Gender",
  saving: "Saving…",
  saveDetails: "Save details",
  demographicsSaved: "Patient demographics were updated.",
  therapistAssignment: "Therapist assignment",
  primaryTherapist: "Primary therapist",
  updateAssignment: "Update assignment",
  assignmentSaved: "Primary therapist assignment was updated.",
  nowUnassigned: "The patient is now unassigned.",
  ownerOnlyReassign: "Only the clinic owner can reassign a patient.",
  careEpisode: "Care episode",
  episodeStatus: (status: string, target: number, started: string) =>
    `Status: ${status} · target ${target}/week · started ${started}`,
  statuses: { active: "active", paused: "paused", completed: "completed" } as Record<string, string>,
  pause: "Pause",
  resume: "Resume",
  complete: "Complete episode",
  resumed:
    "The care episode was resumed. A new prescription must be reviewed and published before patient exercises resume.",
  paused: "The care episode was paused and its actionable prescription was revoked.",
  completed: "The care episode was completed and its clinical artifacts were closed.",
  noEpisode: "No care episode exists yet.",
  newEpisodeTitle: "New episode title",
  daysHint: "1–7 days",
  starting: "Starting…",
  startEpisode: "Start new episode",
  episodeCreated: "A new active care episode was created.",
  portalAccess: "Patient portal access",
  portalHint:
    "The patient (or delegate) signs in at /patient with this mobile number and an SMS code; no email or password is needed. Link only after verifying the number and recording patient consent or legal authority. Delegate access must expire within one year.",
  mobile: "Mobile number",
  mobileHint: "Iranian mobile, e.g. 0912 345 6789",
  relationship: "Relationship",
  relationships: {
    self: "Patient themself",
    parent: "Parent",
    guardian: "Legal guardian",
    caregiver: "Caregiver",
  } as Record<string, string>,
  expiryOptional: "Expiry (optional)",
  expiryRequired: "Expiry (required)",
  attest:
    "I verified this mobile number and attest that patient consent or valid legal authority is recorded outside this application.",
  linking: "Linking…",
  link: "Link portal account",
  attestRequired: "Confirm patient consent/legal authority and set an expiry for every delegate account.",
  invalidMobile: "Enter a valid Iranian mobile number, e.g. 0912 345 6789.",
  linkedCreated: (mobile: string) =>
    `A portal account was created for ${mobile} and linked. The patient signs in at /patient with this number and the SMS code.`,
  linkedExisting: (mobile: string) =>
    `The existing portal account ${mobile} was linked. The patient signs in at /patient with this number and the SMS code.`,
  revokeReason: "Reason required before revoking access",
  noActivePortal: "No active portal account.",
  expires: (date: string) => ` · expires ${date}`,
  noExpiry: " · no expiry",
  revoke: "Revoke access",
  revoked: "Portal access was revoked immediately.",
  archiveTitle: "Archive patient record",
  archiveHint:
    "Archiving retains clinical history, removes assignments and revokes portal access. The database refuses this while alerts are unresolved.",
  archiveReason: "Archive reason",
  archiving: "Archiving…",
  archive: "Archive record",
  archived: "Patient record was archived without deleting clinical history.",
  invite: {
    account_not_eligible:
      "This number belongs to an account that cannot be a patient login: a clinic staff account, an account without a patient profile (e.g. created before the database was reset — run 03_first_clinic_owner.sql again to restore profiles), or the account already represents another patient.",
    create_failed:
      "The portal account could not be created for this number. Check that phone sign-in is enabled in Supabase (Authentication → Providers → Phone) and retry.",
    not_configured:
      "Invitations are not configured on the server: set SUPABASE_SECRET_KEY (server-only) and restart / redeploy.",
    not_permitted:
      "Only a clinic owner of this patient's clinic can link portal accounts, and archived patients cannot be linked.",
    unauthorized: "Your session expired. Sign in again and retry.",
    network: "The server could not be reached. Check the connection and retry.",
    default: "The account could not be linked. Check the number, relationship and expiry, then retry.",
  } as Record<string, string>,
};

export type PatientsText = typeof en;

export const patientsText: PageText<PatientsText> = {
  en,
  fa: {
    title: "فهرست بیماران",
    introShort: "بیماران کلینیک، دوره‌های درمان فعال و فیزیوتراپیست‌های مسئول.",
    intro: "بیماران کلینیک فعال را پیدا کنید، وضعیت درمان را ببینید و دوره درمان جدید را به‌طور امن شروع کنید.",
    demoEmpty: "فهرست نمایشی خالی است",
    demoEmptyHint:
      "حالت نمایشی اطلاعات سلامت ساختگی تولید نمی‌کند. برای استفاده از فهرست، به دیتابیس احراز هویت‌شده کلینیک وصل شوید.",
    checkingAccess: "در حال بررسی دسترسی بالینی…",
    accessRequired: "دسترسی بالینی لازم است",
    accessRequiredHint:
      "اطلاعات سلامت بیمار فقط برای صاحب کلینیک و فیزیوتراپیست‌ها قابل مشاهده است. کارمندان کلینیک و سایر نقش‌ها نمی‌توانند این فهرست را باز کنند.",
    selectClinic: "یک کلینیک فعال انتخاب کنید",
    selectClinicHint: "از نوار بالا کلینیک را انتخاب کنید. پرونده‌ها فقط برای همان کلینیک بارگذاری می‌شوند.",
    closeForm: "بستن فرم",
    newPatient: "بیمار جدید",
    createTitle: "ثبت بیمار و اولین دوره درمان",
    createSubtitle: "در یک تراکنش واحد ذخیره می‌شود؛ پرونده ناقص ایجاد نمی‌شود.",
    fullName: "نام و نام خانوادگی",
    phoneOptional: "تلفن (اختیاری)",
    phoneHint: "۷ تا ۱۵ رقم؛ اعداد فارسی و عربی پذیرفته می‌شوند.",
    birthYearOptional: "سال تولد (اختیاری)",
    birthYearHint: "شمسی (مثلاً ۱۳۶۵) یا میلادی (مثلاً ۱۹۸۶)",
    genderOptional: "جنسیت (اختیاری)",
    notRecorded: "ثبت نشده",
    female: "زن",
    male: "مرد",
    other: "سایر",
    episodeTitle: "عنوان دوره درمان",
    weeklyTarget: "هدف هفتگی",
    weeklyTargetHint: "تعداد جلسات یا روزهای برنامه خانگی در هفته (۱ تا ۷).",
    therapistAutoAssign: "شما به‌طور خودکار فیزیوتراپیست این بیمار خواهید شد.",
    ownerUnassigned: "بیمار جدید بدون فیزیوتراپیست ثبت می‌شود؛ صاحب کلینیک بعداً می‌تواند فیزیوتراپیست تعیین کند.",
    creating: "در حال ثبت…",
    createButton: "ثبت بیمار و دوره درمان",
    createFailed:
      "بیمار ثبت نشد. اتصال و دسترسی‌ها را بررسی کنید و مطمئن شوید تابع create_patient_episode در دیتابیس نصب شده است.",
    created: "بیمار و دوره درمان فعال با هم ثبت شدند.",
    errName2: "حداقل ۲ نویسه وارد کنید.",
    errName120: "نام باید حداکثر ۱۲۰ نویسه باشد.",
    errPhone: "۷ تا ۱۵ رقم وارد کنید (می‌تواند با + شروع شود).",
    errBirthYear: (max) => `سال تولد را بین ۱۹۰۰ و ${max} میلادی یا ۱۲۷۹ تا ${max - 621} شمسی وارد کنید.`,
    errTitle2: "حداقل ۲ نویسه وارد کنید.",
    errTitle160: "عنوان دوره باید حداکثر ۱۶۰ نویسه باشد.",
    errWeekly: "هدف هفتگی باید عددی صحیح از ۱ تا ۷ باشد.",
    searchLabel: "جستجوی نام بیمار",
    searchPlaceholder: "جستجو بر اساس نام بیمار…",
    search: "جستجو",
    clear: "پاک کردن",
    refresh: "تازه‌سازی",
    loadingPatients: "در حال بارگذاری بیماران کلینیک…",
    loadFailed: "فهرست بیماران بارگذاری نشد. اتصال و دسترسی کلینیک را بررسی و دوباره تلاش کنید.",
    tryAgain: "تلاش دوباره",
    noMatches: "بیماری با این نام پیدا نشد",
    noPatients: "هنوز بیماری در این کلینیک ثبت نشده",
    noMatchesHint: "نام دیگری امتحان کنید یا جستجو را پاک کنید.",
    noPatientsHint: "اولین بیمار و دوره درمان فعال را ثبت کنید.",
    clearSearch: "پاک کردن جستجو",
    caption: "بیماران کلینیک فعال با دوره درمان و فیزیوتراپیست مسئول",
    colPatient: "بیمار",
    colDemographics: "مشخصات",
    colEpisode: "دوره درمان فعال",
    colTherapist: "فیزیوتراپیست مسئول",
    colAdded: "تاریخ ثبت",
    colActions: "عملیات",
    noPhone: "تلفن ثبت نشده",
    born: (year, age) => `متولد ${year} · حدود ${age} سال`,
    noBirthYear: "سال تولد ثبت نشده",
    targetSince: (target, since) => `هدف ${target} روز در هفته · از ${since}`,
    noActiveEpisode: "دوره درمان فعال ندارد",
    unassigned: "تعیین نشده",
    manage: "مدیریت",
    workspace: "میز کار",
    showing: (first, last, total) => `نمایش ${first} تا ${last} از ${total}`,
    previous: "قبلی",
    next: "بعدی",
    previousAria: "صفحه قبلی بیماران",
    nextAria: "صفحه بعدی بیماران",
    pageOf: (page, total) => `صفحه ${page} از ${total}`,
    unknownDate: "نامشخص",
    manageTitle: (name) => `مدیریت ${name}`,
    manageSubtitle: "همه تغییرات دوره درمان و پرتال توسط دیتابیس مجوزدهی و ثبت می‌شود.",
    close: "بستن",
    changeRejected: "تغییر پذیرفته نشد. دسترسی‌ها، وضعیت دوره درمان و migration 015 را بررسی کنید.",
    demographics: "مشخصات",
    phone: "تلفن",
    birthYear: "سال تولد",
    gender: "جنسیت",
    saving: "در حال ذخیره…",
    saveDetails: "ذخیره مشخصات",
    demographicsSaved: "مشخصات بیمار به‌روز شد.",
    therapistAssignment: "تعیین فیزیوتراپیست",
    primaryTherapist: "فیزیوتراپیست اصلی",
    updateAssignment: "ثبت فیزیوتراپیست",
    assignmentSaved: "فیزیوتراپیست اصلی به‌روز شد.",
    nowUnassigned: "اکنون فیزیوتراپیستی برای بیمار تعیین نشده است.",
    ownerOnlyReassign: "فقط صاحب کلینیک می‌تواند فیزیوتراپیست بیمار را تغییر دهد.",
    careEpisode: "دوره درمان",
    episodeStatus: (status, target, started) =>
      `وضعیت: ${status} · هدف ${target} روز در هفته · شروع ${started}`,
    statuses: { active: "فعال", paused: "متوقف", completed: "پایان‌یافته" },
    pause: "توقف موقت",
    resume: "ادامه",
    complete: "پایان دوره درمان",
    resumed: "دوره درمان ادامه یافت. پیش از ادامه تمرین‌های بیمار، نسخه تمرین جدید باید بازبینی و منتشر شود.",
    paused: "دوره درمان متوقف شد و نسخه تمرین فعال آن لغو شد.",
    completed: "دوره درمان پایان یافت و موارد بالینی آن بسته شد.",
    noEpisode: "هنوز دوره درمانی ثبت نشده است.",
    newEpisodeTitle: "عنوان دوره جدید",
    daysHint: "۱ تا ۷ روز",
    starting: "در حال شروع…",
    startEpisode: "شروع دوره جدید",
    episodeCreated: "دوره درمان فعال جدید ایجاد شد.",
    portalAccess: "دسترسی پرتال بیمار",
    portalHint:
      "بیمار (یا همراه او) با این شماره همراه و کد پیامکی در /patient وارد می‌شود؛ ایمیل یا رمز لازم نیست. فقط پس از بررسی شماره و ثبت رضایت بیمار یا اختیار قانونی، حساب را وصل کنید. دسترسی همراه باید حداکثر یک‌ساله باشد.",
    mobile: "شماره همراه",
    mobileHint: "شماره همراه ایرانی، مثلاً ۰۹۱۲ ۳۴۵ ۶۷۸۹",
    relationship: "نسبت",
    relationships: {
      self: "خود بیمار",
      parent: "والد",
      guardian: "قیم قانونی",
      caregiver: "مراقب",
    },
    expiryOptional: "تاریخ انقضا (اختیاری)",
    expiryRequired: "تاریخ انقضا (الزامی)",
    attest:
      "این شماره همراه را بررسی کرده‌ام و تأیید می‌کنم رضایت بیمار یا اختیار قانونی معتبر خارج از این برنامه ثبت شده است.",
    linking: "در حال اتصال…",
    link: "اتصال حساب پرتال",
    attestRequired: "رضایت بیمار/اختیار قانونی را تأیید کنید و برای هر حساب همراه تاریخ انقضا تعیین کنید.",
    invalidMobile: "شماره همراه ایرانی معتبر وارد کنید، مثلاً ۰۹۱۲ ۳۴۵ ۶۷۸۹.",
    linkedCreated: (mobile) =>
      `حساب پرتال برای ${mobile} ساخته و وصل شد. بیمار با همین شماره و کد پیامکی در /patient وارد می‌شود.`,
    linkedExisting: (mobile) =>
      `حساب پرتال موجود ${mobile} وصل شد. بیمار با همین شماره و کد پیامکی در /patient وارد می‌شود.`,
    revokeReason: "دلیل لغو دسترسی (الزامی)",
    noActivePortal: "حساب پرتال فعالی وجود ندارد.",
    expires: (date) => ` · انقضا ${date}`,
    noExpiry: " · بدون انقضا",
    revoke: "لغو دسترسی",
    revoked: "دسترسی پرتال بلافاصله لغو شد.",
    archiveTitle: "بایگانی پرونده بیمار",
    archiveHint:
      "بایگانی، سوابق بالینی را نگه می‌دارد، تخصیص‌ها را حذف و دسترسی پرتال را لغو می‌کند. تا وقتی هشدار حل‌نشده وجود دارد، دیتابیس اجازه نمی‌دهد.",
    archiveReason: "دلیل بایگانی",
    archiving: "در حال بایگانی…",
    archive: "بایگانی پرونده",
    archived: "پرونده بیمار بدون حذف سوابق بالینی بایگانی شد.",
    invite: {
      account_not_eligible:
        "این شماره متعلق به حسابی است که نمی‌تواند حساب بیمار باشد: حساب کارمند کلینیک، حساب بدون پروفایل بیمار (مثلاً ساخته‌شده پیش از ریست دیتابیس — فایل 03_first_clinic_owner.sql را دوباره اجرا کنید)، یا حسابی که از قبل به بیمار دیگری وصل است.",
      create_failed:
        "حساب پرتال برای این شماره ساخته نشد. بررسی کنید ورود با تلفن در Supabase فعال باشد (Authentication → Providers → Phone) و دوباره تلاش کنید.",
      not_configured:
        "دعوت در سرور تنظیم نشده است: SUPABASE_SECRET_KEY را (فقط سمت سرور) تنظیم و دوباره Deploy کنید.",
      not_permitted:
        "فقط صاحب کلینیکِ این بیمار می‌تواند حساب پرتال وصل کند و بیمار بایگانی‌شده قابل اتصال نیست.",
      unauthorized: "نشست شما منقضی شده است. دوباره وارد شوید و تلاش کنید.",
      network: "ارتباط با سرور برقرار نشد. اتصال را بررسی و دوباره تلاش کنید.",
      default: "حساب وصل نشد. شماره، نسبت و تاریخ انقضا را بررسی و دوباره تلاش کنید.",
    },
  },
};
