import type { PageText } from "@/lib/i18n/text";

const en = {
  unknownDate: "Unknown date",
  discardConfirm: "Discard the unsaved clinical note or outcome draft before changing patient context?",
  needContent: "Enter clinical content; a correction also requires a reason.",
  invalidTime: "Choose a valid session date and time.",
  sessionFailed: "Session note was not signed. Check assignment, content and connection; the draft remains here.",
  sessionSaved: "Signed session note appended to the record.",
  outcomeInvalid: "Choose a reviewed measure and enter a score in its range.",
  outcomeFailed: "Outcome was not signed. Check assignment, date and reviewed score range; the draft remains here.",
  outcomeSaved: "Versioned outcome measurement appended to the record.",
  replaceSession: "Replace the unsaved session-note draft with this correction?",
  replaceOutcome: "Replace the unsaved outcome-measure draft with this correction?",
  correctionMode: "Correction mode: the signed original remains in history.",
  title: "Clinical Records",
  demoIntro: "Signed session notes and validated outcome measurements.",
  demoTitle: "No fabricated clinical documentation",
  demoBody:
    "This append-only workflow is available only with authenticated Supabase and migration 018. Demo mode does not invent signed notes or scores.",
  shortIntro: "Signed clinical documentation.",
  accessTitle: "Clinical access required",
  accessBody: "Only clinic owners and assigned therapists can read or append this record.",
  clinicTitle: "Select an active clinic",
  clinicBody: "Choose the tenant before opening patient documentation.",
  intro:
    "Append-only session documentation and versioned, range-checked outcome measures. Corrections never overwrite the signed original.",
  patientEpisode: "Patient and care episode",
  searchPlaceholder: "Search patient name",
  search: "Search",
  loadingPatients: "Loading authorized patients…",
  patientsFailed: "Patient list could not be loaded. This is not an empty registry; check the connection and retry.",
  retryPatients: "Retry patient list",
  patient: "Patient",
  patientHint: "Only patients visible through the active clinic and current assignment are listed.",
  selectPatient: "Select a patient",
  noEpisode: "No episode",
  activeEpisode: "active episode",
  historicalEpisode: "historical episode",
  chooseTitle: "Choose a patient with a care episode",
  chooseBody: "The signed timeline is scoped to one explicit episode.",
  correctSession: "Correct session note",
  signSession: "Sign session note",
  sessionSubtitle: "SOAP-style fields remain immutable after signing.",
  sessionTime: "Session date and time",
  fields: {
    subjective: "Subjective",
    objective: "Objective",
    interventions: "Interventions",
    response: "Response",
    plan: "Plan",
  } as Record<string, string>,
  correctionReason: "Correction reason",
  signing: "Signing…",
  appendNote: "Append signed note",
  cancelCorrection: "Cancel correction",
  correctOutcome: "Correct outcome",
  recordOutcome: "Record outcome",
  outcomeSubtitle: "Instrument version, unit and scoring range are stamped by the database.",
  catalogFailed: "The reviewed outcome-measure catalog could not be loaded. No score can be signed until it is available.",
  retryCatalog: "Retry instrument catalog",
  noInstruments: "No active reviewed outcome instruments are configured. Ask the platform administrator to verify migration 018.",
  instrument: "Reviewed instrument",
  loadingInstruments: "Loading reviewed instruments…",
  selectInstrument: "Select an instrument",
  score: "Score",
  measuredDate: "Measured date",
  clinicalNote: "Clinical note",
  appendOutcome: "Append outcome",
  timeline: "Signed timeline",
  loadingDocs: "Loading signed documentation…",
  docsFailed: "Documentation could not be loaded. Existing rows are not shown as current.",
  retryTimeline: "Retry signed timeline",
  noDocs: "No signed documentation for this episode yet.",
  sessionNotes: "Session notes",
  current: "current",
  superseded: "superseded",
  correction: (reason: string) => `Correction: ${reason}`,
  createCorrection: "Create correction",
  outcomes: "Outcome measures",
  measuredVersion: (date: string, version: number) => `${date} · version ${version}`,
  range: (min: number, max: number, direction: string) => `Reviewed range ${min}–${max}; ${direction}.`,
  directions: { "higher-better": "higher better", "higher-worse": "higher worse" } as Record<string, string>,
};

export type ClinicalRecordsText = typeof en;

export const clinicalRecordsText: PageText<ClinicalRecordsText> = {
  en,
  fa: {
    unknownDate: "تاریخ نامشخص",
    discardConfirm: "پیش از تغییر بیمار، پیش‌نویس ذخیره‌نشده یادداشت یا پیامد حذف شود؟",
    needContent: "محتوای بالینی وارد کنید؛ برای اصلاح، دلیل هم لازم است.",
    invalidTime: "تاریخ و ساعت معتبر جلسه را انتخاب کنید.",
    sessionFailed: "یادداشت جلسه امضا نشد. تخصیص، محتوا و اتصال را بررسی کنید؛ پیش‌نویس روی صفحه باقی است.",
    sessionSaved: "یادداشت امضاشده جلسه به پرونده افزوده شد.",
    outcomeInvalid: "یک ابزار بازبینی‌شده انتخاب کنید و نمره را در محدوده آن وارد کنید.",
    outcomeFailed: "پیامد امضا نشد. تخصیص، تاریخ و محدوده نمره را بررسی کنید؛ پیش‌نویس روی صفحه باقی است.",
    outcomeSaved: "سنجش پیامد نسخه‌دار به پرونده افزوده شد.",
    replaceSession: "پیش‌نویس ذخیره‌نشده یادداشت جلسه با این اصلاح جایگزین شود؟",
    replaceOutcome: "پیش‌نویس ذخیره‌نشده سنجش پیامد با این اصلاح جایگزین شود؟",
    correctionMode: "حالت اصلاح: نسخه امضاشده اصلی در تاریخچه باقی می‌ماند.",
    title: "پرونده بالینی",
    demoIntro: "یادداشت‌های امضاشده جلسات و سنجش‌های پیامد معتبر.",
    demoTitle: "مستندات بالینی ساختگی تولید نمی‌شود",
    demoBody:
      "این روند فقط‌افزودنی تنها با Supabase احراز هویت‌شده و migration 018 در دسترس است. حالت نمایشی یادداشت یا نمره امضاشده ساختگی نمی‌سازد.",
    shortIntro: "مستندات بالینی امضاشده.",
    accessTitle: "دسترسی بالینی لازم است",
    accessBody: "فقط صاحب کلینیک و فیزیوتراپیست مسئول می‌توانند این پرونده را ببینند یا به آن اضافه کنند.",
    clinicTitle: "یک کلینیک فعال انتخاب کنید",
    clinicBody: "پیش از باز کردن مستندات بیمار، کلینیک را انتخاب کنید.",
    intro:
      "مستندات جلسات فقط‌افزودنی و سنجش‌های پیامد نسخه‌دار با کنترل محدوده. اصلاح هرگز نسخه امضاشده اصلی را بازنویسی نمی‌کند.",
    patientEpisode: "بیمار و دوره درمان",
    searchPlaceholder: "جستجوی نام بیمار",
    search: "جستجو",
    loadingPatients: "در حال بارگذاری بیماران مجاز…",
    patientsFailed: "فهرست بیماران بارگذاری نشد. این به معنای خالی بودن فهرست نیست؛ اتصال را بررسی و دوباره تلاش کنید.",
    retryPatients: "بارگذاری دوباره بیماران",
    patient: "بیمار",
    patientHint: "فقط بیمارانی که از طریق کلینیک فعال و تخصیص فعلی قابل مشاهده‌اند نمایش داده می‌شوند.",
    selectPatient: "انتخاب بیمار",
    noEpisode: "بدون دوره",
    activeEpisode: "دوره فعال",
    historicalEpisode: "دوره گذشته",
    chooseTitle: "بیماری با دوره درمان انتخاب کنید",
    chooseBody: "خط زمانی امضاشده به یک دوره درمان مشخص محدود است.",
    correctSession: "اصلاح یادداشت جلسه",
    signSession: "امضای یادداشت جلسه",
    sessionSubtitle: "فیلدهای SOAP پس از امضا تغییرناپذیرند.",
    sessionTime: "تاریخ و ساعت جلسه",
    fields: {
      subjective: "ذهنی (S)",
      objective: "عینی (O)",
      interventions: "مداخلات",
      response: "پاسخ بیمار",
      plan: "برنامه (P)",
    },
    correctionReason: "دلیل اصلاح",
    signing: "در حال امضا…",
    appendNote: "افزودن یادداشت امضاشده",
    cancelCorrection: "انصراف از اصلاح",
    correctOutcome: "اصلاح پیامد",
    recordOutcome: "ثبت پیامد",
    outcomeSubtitle: "نسخه ابزار، واحد و محدوده نمره توسط دیتابیس ثبت می‌شود.",
    catalogFailed: "فهرست ابزارهای سنجش پیامد بارگذاری نشد. تا در دسترس شدن آن هیچ نمره‌ای امضا نمی‌شود.",
    retryCatalog: "بارگذاری دوباره فهرست ابزارها",
    noInstruments: "هیچ ابزار سنجش پیامد فعالی تنظیم نشده است. از مدیر پلتفرم بخواهید migration 018 را بررسی کند.",
    instrument: "ابزار بازبینی‌شده",
    loadingInstruments: "در حال بارگذاری ابزارها…",
    selectInstrument: "انتخاب ابزار",
    score: "نمره",
    measuredDate: "تاریخ سنجش",
    clinicalNote: "یادداشت بالینی",
    appendOutcome: "افزودن پیامد",
    timeline: "خط زمانی امضاشده",
    loadingDocs: "در حال بارگذاری مستندات امضاشده…",
    docsFailed: "مستندات بارگذاری نشد. ردیف‌های موجود به‌عنوان وضعیت فعلی نمایش داده نمی‌شوند.",
    retryTimeline: "بارگذاری دوباره خط زمانی",
    noDocs: "هنوز مستند امضاشده‌ای برای این دوره ثبت نشده است.",
    sessionNotes: "یادداشت‌های جلسه",
    current: "فعلی",
    superseded: "جایگزین‌شده",
    correction: (reason) => `اصلاح: ${reason}`,
    createCorrection: "ثبت اصلاحیه",
    outcomes: "سنجش‌های پیامد",
    measuredVersion: (date, version) => `${date} · نسخه ${version}`,
    range: (min, max, direction) => `محدوده بازبینی‌شده ${min} تا ${max}؛ ${direction}.`,
    directions: { "higher-better": "نمره بالاتر بهتر", "higher-worse": "نمره بالاتر بدتر" },
  },
};
